### ISSUE TITLE
Restart command

### ISSUE THREAD

**Issue by qrevel** [ueokande/vim-vixen#100]
### I'm opening this issue because:

- I'll propose a new feature

### Description

A restart command to restart Firefox (vimperator feature here).
It's usefull when configuring addons in Firefox that needs a restart.

#### System configuration

- Operating system: MacOS High Sierra
- Firefox version: 57
- Vim-Vixen version: 0.3

**Comment by ainola** [comment]
Do webextension addons ever need firefox to restart?

**Comment by qrevel** [comment]
Vixen needed a restart if I remember correctly. To be honest I didn't test on other addons.

**Comment by gliptak** [comment]
I just added ```Vim Vixen``` and I didn't have to restart.

https://blog.mozilla.org/addons/2016/08/15/restart-required/

**Comment by qrevel** [comment]
Ok I'm closing the issue because I don't see any other use case.
