### ISSUE TITLE
Use D instead of dK

### ISSUE THREAD

**Issue by qrevel** [ueokande/vim-vixen#102]
### I'm opening this issue because:

- I'll propose a new feature

### Description

When you delete a tab with `d`, the next tab is selected.
If you want to go to the previous tab, you need to type `dK`.
`D` saves one keystroke 😄 .

#### System configuration

- Operating system: MacOS High Sierra
- Firefox version: 57
- Vim-Vixen version: 0.3

**Comment by ainola** [comment]
This may be of some use for reference purposes:

https://github.com/e10s/focus-on-left-tab-after-closing/blob/master/background.js

**Comment by mvhulten** [comment]
As a comment to #260, I suggest to remove the `d` binding.  Maybe implementing *only* the `D` binding would be an idea.

Is there a sort of meta-issue already that discusses the best set of bindings?  The [xombrero bindings](http://manpages.org/xombrero) were intuitive to me.  This web browser is discontinued.
