### ISSUE TITLE
[tab]open not responsive while typing

### ISSUE THREAD

**Issue by nucatus** [ueokande/vim-vixen#1024]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description
When trying opening a new tab or window using the `open` command, typing is impaired by the _search as you type_ functionality, especially if you have a large search base, like long history or many bookmarks. 

I'd recommend introducing a hysteresis when typing that will run a search only after a particular timeout after a key was pressed. 

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

#### System configuration

- Operating system: OSX 11
- Firefox version: 86.0
- Vim-Vixen version: 0.32

#### Console logs

Any relevant log in developer tools:

**Comment by nucatus** [comment]
I see this issue was already addressed in an old PR #502. Would it be possible to get this merged? This looks to solve the issue with using the console.

**Comment by wolfisberg** [comment]
Maybe this should be configurable. The PR hardcoded the delay to 150 ms, which would just make the console less responsive for people who don't suffer from this issue.

**Comment by nucatus** [comment]
There definitely should be a hysteresis with every keystroke if search results can not be provided at a speed that wouldn't impair the typing experience.

**Comment by ueokande** [comment]
fixed in #1099
