### ISSUE TITLE
hide/replace botoom left status bar

### ISSUE THREAD

**Issue by nucatus** [ueokande/vim-vixen#1025]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description
Firefox' status bar interferes with vim vixen console.

When using the console, in case firefox needs to display the status bar, this hides the vim-vixen console, making it unusable. 

A solution would to hide the status bar while the console is in use.  For this, see this [post](https://support.mozilla.org/en-US/questions/1285060), to to reposition it on top of the vim-vixen console, if the console is shown. 

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

#### System configuration

- Operating system: OSX 11
- Firefox version: 86.0
- Vim-Vixen version: 0.32

#### Console logs

Any relevant log in developer tools:

**Comment by ueokande** [comment]
Thank you for your report.  The issue is reported on #203.

**Comment by vuongkienthanh** [comment]
Instead of replacing/hiding firefox's statusbar, how about we move the console 1 line upward?
The solutions above and on #203 don't work for me. I tried putting the chrome/userChrome.css file in both .default and .default-release folder.
