### ISSUE TITLE
Flickering like issue

### ISSUE THREAD

**Issue by antenore** [ueokande/vim-vixen#103]
### I'm opening this issue because:

- [ x] I'll report a bug
- [ ] I'll propose a new feature

### Description

Every minute or so,  each tab becomes  black for few milliseconds. 
What can I do to help debugging? 

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

#### System configuration

- Operating system:
- Firefox version:
- Vim-Vixen version:

#### Console logs

Any relevant log in developer tools:

**Comment by ainola** [comment]
Are you sure this an issue with this extension? This sounds like a general graphics issue. Does this behavior exhibit itself only with the extension installed?

**Comment by antenore** [comment]
No, I'm not sure. I'll do more debugging later. I've reported it because it's the last extention I've installed.

**Comment by antenore** [comment]
You were right, sorry, I've updated firefox to the last nigthly build and the problem is disappeared.

**Comment by antenore** [comment]
Just as a followup. It was the Stylish addon, I've removed it and installed the new one (Stylus beta) and the flickering disappeared.

Thanks gain for this fantastic addon!!!
