### ISSUE TITLE
Add-on doesn't verify on firefox 56

### ISSUE THREAD

**Issue by Luftzig** [ueokande/vim-vixen#108]
### I'm opening this issue because:

- [ X ] I'll report a bug
- [ ] I'll propose a new feature

### Failure Information (for bugs)

Can not install

#### Steps to Reproduce

1. When using Firefox 56 Ubuntu build
2. Go to the official mozilla addons page: https://addons.mozilla.org/en-US/firefox/addon/vim-vixen/?src=search
3. Click "Add to Firefox" button
4. Add on will be downloaded but download window will stay stuck on "verifying add on". It will not be added.

#### System configuration

Firefox 56.0 Ubuntu build, 64bit, on Ubuntu 17.10 and 17.04

- Operating system:
- Firefox version:
- Vim-Vixen version:

#### Console logs

Any relevant log in developer tools:

**Comment by ueokande** [comment]
@Luftzig Firefox 56.0 is not longer supported.  Does this issue still occues on Firefox 57?

**Comment by chocolateboy** [comment]
It's working for me on Firefox 56.0.2 (Arch Linux).
