### ISSUE TITLE
Does not work with the Dark Background and Light Text addon

### ISSUE THREAD

**Issue by mguzmann** [ueokande/vim-vixen#109]
### I'm opening this issue because:

- [x] I'll report a bug

### Description

When using https://addons.mozilla.org/es/firefox/addon/dark-background-light-text/ with vim-vixen the whole webpage becomes a single solid background. The problem goes away when I deactivate vim-vixen.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. install dark background light text
2. install vim-vixen
3. completely dark webpage (text not showing)

#### System configuration

- Ubuntu 17.04
- Firefox 56.0
- Vim-Vixen version: 0.3

**Comment by qazip** [comment]
This is also happening to me. It should be noted, however, that this happens only with the "Simple CSS" option, in the dark background extension.

**Comment by ueokande** [comment]
This issues was fixed in #1034 and #1043.
