### ISSUE TITLE
It is impossible to open native Firefox URLs with the command :open.

### ISSUE THREAD

**Issue by lucasmsoares96** [ueokande/vim-vixen#1153]
### I'm opening this issue because:

- I'll report a bug

### Description
It is impossible to open native Firefox URLs, for example about:config, with the command :open.

### Failure Information (for bugs):
Illegal URL: about:config

#### Steps to Reproduce
:open about:config

#### System configuration

- Operating system: Linux GentooLinux 5.11.18-gentoo-dist #1 SMP Sun May 2 17:33:02 -00 2021 x86_64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz GenuineIntel GNU/Linux
- Firefox version: Mozilla Firefox 88.0
- Vim-Vixen version: 1.2.0

**Comment by ueokande** [comment]
It it an extension limitation.  see also #106
