### ISSUE TITLE
Pasting URLs stopped working with FF 89

### ISSUE THREAD

**Issue by richardb64** [ueokande/vim-vixen#1188]
The pasting of URLs from the clipboard with the "p" and "P" keys has stopped working.  This seems to be related to the latest Firefox update to version 89 ("Proton").  The effect is that both keystrokes open a blank Google search page (initially https://google.com/search?q= which then redirects to https://www.google.com/webhp).

I don't think it's simply that some other extension, or Firefox itself, is grabbing the keystrokes, because "p" and "P" still have the correct behaviour of loading the new page in the current or a new tab respectively.  It's as if VV is no longer able to read the clipboard.

The Vim Vixen key mappings are the defaults:
```
    "p": {
      "type": "urls.paste",
      "newTab": false
    },
    "P": {
      "type": "urls.paste",
      "newTab": true
    },
```

There's nothing obvious in the FF console.

Digging a little, VV currently works by creating a hidden textarea and invoking `window.document.execCommand("paste");` to fill it.  There is also now a Clipboard class that ought to be able to do the same thing more directly, though perhaps the "paste" method is needed for wider compatibility with other browsers.  Either way, the Mozilla docs say that the relevant permission is called "clipboard-read" - but looking at the manifest, VV is only requesting "clipboardRead".  Mozilla's own documentation seems inconsistent on the spelling of the permission, so would it be worth VV requesting both?

There's also a suspicious bug https://bugzilla.mozilla.org/show_bug.cgi?id=1220696 which apparently, from FF89, removes the need to use workarounds for `Document.execCommand("insertText")` to work with textareas.  Has this fix somehow broken the way that VV uses "paste"?

I've tried toggling `dom.events.asyncClipboard.clipboardItem` but that doesn't seem to make any difference.

Possibly related, I've also noticed that VV paste seems to unconditionally use the primary _search_ rather than just going to the URL as given.  I think that's bad, because by definition paste is supposed to paste explicit URLs, and going via a search engine is a huge privacy violation.  I suppose it's consistent with the overloading of the address bar in the graphical UI, but personally I think that's wrong too!

#### System configuration

- Operating system: Windows 10 version 21H1 build 19043.1052
- Firefox version: 89 build 20210527174632
- Vim-Vixen version: 1.2.0 from AMO

**Comment by ueokande** [comment]
@richardb64 Thank you for your reporting!  The issues is fixed in v1.2.1.
