### ISSUE TITLE
Navigation/scrolling not working on some sites

### ISSUE THREAD

**Issue by thojaco** [ueokande/vim-vixen#122]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description

As the title says, navigation with j and k doesnt work on some websites. news.ycombinator.com is an example. Everything else works (search, open new tab, next/prev tab, etc).

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Simply open news.ycombinator.com or any subsite, and try to navigate with j and k.

#### System configuration

- Operating system: macOS 10.12.6
- Firefox version: 56.0.2 (64 bit)
- Vim-Vixen version: 0.3

**Comment by ueokande** [comment]
It is duplicated with #107; that will be fixed on v0.4 release.
