### ISSUE TITLE
Page scrolling doesn't work on https://news.ycombinator.com

### ISSUE THREAD

**Issue by danjac** [ueokande/vim-vixen#128]
### I'm opening this issue because:

- [x ] I'll report a bug
- [ ] I'll propose a new feature

### Description

Unable to scroll using keyword commands on all pages of this site.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

- Go to https://news.ycombinator.com/
- Page scrolling using j, k, gg etc does not work (nothing happens). Other actions are OK e.g. "f". 

#### System configuration

- Operating system: Linux/Fedora 26
- Firefox version: 57 (Beta)
- Vim-Vixen version: 0.3

#### Console logs

Any relevant log in developer tools:

**Comment by ueokande** [comment]
It is duplicated with #107; that will be fixed on v0.4 release.
