### ISSUE TITLE
Add support for opening a blank tab

### ISSUE THREAD

**Issue by rkratky** [ueokande/vim-vixen#130]
### I'm opening this issue because:

- [x] I'll propose a new feature

### Description

It would be nice to have the possibility to configure opening a new blank tab, such as

`"n": { "type": "tabs.open" }`

**Comment by TheReverend403** [comment]
This would actually solve my one problem with vixen, which is not being able to focus the address bar to use Firefox's native suggestions. With the ability to open a new tab, I could take advantage of the fact Firefox focuses the address bar on new tabs by default to workaround this issue, which is a limitation of the extension API as far as I know.

**Comment by reading123** [comment]
This is far more useful than the vim vixen :tabopen command currently (no offense, it's a limitation of the webextension api like you said).

Currently I'm using https://github.com/pmalecka/chrome-shortkeys to add this functionality: simply add a shortcut within that addon and remove the shortcut from vim vixen so there's no overlap. I have a suggestion:

Replace tabopen with just opening a new, blank tab (if webextension allows), and open "o" with opening a new, blank tab while deleting the current tab. This allows for the functionality that people are missing from the firefox url bar (and vimfx, etc.) and should be simpler to maintain, no need for including that search engine stuff in vim vixen. Which, by the way is another annoying thing, no doubt it's a limitation of the webextension api again that vim vixen can't view my default search engine, but I now have to go change it two places in the settings.

Another thing you may consider is the functionality offered by "keyboard savior xtreme" plugin, which saves me a few extra seconds on sites that want to grab the keyboard (such as Github). Previously on vimfx you could simply hit esc and then get vimfx features back but now that's not reliable, and vim vixen wasn't always working on all sites. That "keyboard savior xtreme" plugin solved that for me.

**Comment by stupidus89** [comment]
I would also like to be have an command to open a new tab with one keypress. Below is just an alternative, **complementary** suggestion to achieve this feature:

Could it be possible to use `:tabopen` to open a new tab? Right now, pressing `t` and then `Enter` will search for an empty string using the default searchengine. Could it be possible to add a check if the string is empty and then open a new tab instead of the default search engine?

**Comment by ueokande** [comment]
Opening home page is now supported in #511.  Set `about:blank` to home-page URL and press <kbd>g</kbd><kbd>H</kbd>.

If this issue is still valid, please open a new issues.  Thank you for your proposal.
