### ISSUE TITLE
Disbale addon for specific websites manually

### ISSUE THREAD

**Issue by meikse** [ueokande/vim-vixen#1331]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description

since duckduckgo (i.e.) or other websites already come with a kind of vim navigation, I would suggest that it should be possible to permanently disable this addon for some websites manually. If this feature already exists, than I want to apologize and would be glad if someone could explain me how to utilize this. Until now I could not find anything in the documentation.

Thanks you very much

**Comment by ueokande** [comment]
Blcklist allows you to disable the addon by url pattern.  Please refer [the document](https://ueokande.github.io/vim-vixen/blacklist.html).
