### ISSUE TITLE
Does not work on all pages?

### ISSUE THREAD

**Issue by rahulthewall** [ueokande/vim-vixen#139]
### I'm opening this issue because:

- [x] I'll report a bug

### Description

A short list of webpages where it does not seem to work
- http://www.espncricinfo.com/ (Can't open console)
- https://addons.mozilla.org/en-US/firefox/ (Can't do anything)

#### System configuration

- Operating system: OS X 10.12.6
- Firefox version: 58.0a1 (2017-11-05) (64-bit)
- Vim-Vixen version: 0.4

**Comment by ueokande** [comment]
Is it security reason for addons.mozilla.org?

**Comment by rahulthewall** [comment]
How do I check that?

**Comment by ueokande** [comment]
I'm not sure since not Firefox developer, but the following file seems blacklist for add-ons: 
 https://dxr.mozilla.org/mozilla-central/source/browser/app/permissions

**Comment by rafaelleru** [comment]
in whatsapp web doesn't work neither.

**Comment by rafaelleru** [comment]
and doesn't work neither in tabs suspended by tab suspender

**Comment by kirienko** [comment]
I have the same bug.
### Even easier *steps to reproduce*:
In my case it is the following:
1. `:tabopen about:blank`
2. Blank page opens in a new tab
3. I cannot do anything with this tab from the keyboard: `d`, `t`, `o` or any other plugin's bindings just don't work.
### System configuration
* OS X 10.12.6
* Firefox 56.0.2
* Vim-Vixen version: 0.4

**Comment by ueokande** [comment]
Probably, it is able to enable plugin on `about:blank`.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/content_scripts

**Comment by rafaelleru** [comment]
I can't understand you @ueokande how I can enable the plugin globally??

**Comment by ueokande** [comment]
It is required to fix the plugin, please wait the newer releases.
