### ISSUE TITLE
cannot save JSON configuration

### ISSUE THREAD

**Issue by japhir** [ueokande/vim-vixen#143]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description

When configuring the extension, I cannot get the JSON file to be saved. I update it (include a new search engine, add a blacklist) but there is no button to save the file. When I return to the settings page after closing it, it returns to the default.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
install vim-vixen
2. step 2
go to configuration, adjust JSON file, ... close tab
3. you get it...
it doesn't save the configuration

#### System configuration

- Operating system: Arch Linux
- Firefox version: 57.0
- Vim-Vixen version: 0.4

#### Console logs

Any relevant log in developer tools:

**Comment by japhir** [comment]
My desired config file, may be relevant:

```
{
  "keymaps": {
    "0": { "type": "scroll.home" },
    ":": { "type": "command.show" },
    "o": { "type": "command.show.open", "alter": false },
    "O": { "type": "command.show.open", "alter": true },
    "t": { "type": "command.show.tabopen", "alter": false },
    "T": { "type": "command.show.tabopen", "alter": true },
    "w": { "type": "command.show.winopen", "alter": false },
    "W": { "type": "command.show.winopen", "alter": true },
    "b": { "type": "command.show.buffer" },
    "k": { "type": "scroll.vertically", "count": -1 },
    "j": { "type": "scroll.vertically", "count": 1 },
    "h": { "type": "scroll.horizonally", "count": -1 },
    "l": { "type": "scroll.horizonally", "count": 1 },
    "<C-Y>": { "type": "scroll.vertically", "count": -1 },
    "<C-E>": { "type": "scroll.vertically", "count": 1 },
    "<C-U>": { "type": "scroll.pages", "count": -0.5 },
    "<C-D>": { "type": "scroll.pages", "count": 0.5 },
    "<C-B>": { "type": "scroll.pages", "count": -1 },
    "<C-F>": { "type": "scroll.pages", "count": 1 },
    "gg": { "type": "scroll.top" },
    "G": { "type": "scroll.bottom" },
    "$": { "type": "scroll.end" },
    "d": { "type": "tabs.close" },
    "u": { "type": "tabs.reopen" },
    "K": { "type": "tabs.prev", "count": 1 },
    "J": { "type": "tabs.next", "count": 1 },
    "r": { "type": "tabs.reload", "cache": false },
    "R": { "type": "tabs.reload", "cache": true },
    "zi": { "type": "zoom.in" },
    "zo": { "type": "zoom.out" },
    "zz": { "type": "zoom.neutral" },
    "f": { "type": "follow.start", "newTab": false },
    "F": { "type": "follow.start", "newTab": true },
    "H": { "type": "navigate.history.prev" },
    "L": { "type": "navigate.history.next" },
    "[[": { "type": "navigate.link.prev" },
    "]]": { "type": "navigate.link.next" },
    "gu": { "type": "navigate.parent" },
    "gU": { "type": "navigate.root" },
    "y": { "type": "urls.yank" },
    "<S-Esc>": { "type": "addon.toggle.enabled" }
  },
  "search": {
    "default": "startpage",
    "engines": {
      "startpage": "https://startpage.com/do/dsearch?query={}"
      "google": "https://google.com/search?q={}",
      "yahoo": "https://search.yahoo.com/search?p={}",
      "bing": "https://www.bing.com/search?q={}",
      "duckduckgo": "https://duckduckgo.com/?q={}",
      "twitter": "https://twitter.com/search?q={}",
      "wikipedia": "https://en.wikipedia.org/w/index.php?search={}"
    }
  },
  "blacklist": [
    "*mail.google.com/*",
    "*calendar.google.com/*",
  ]
}
```

**Comment by ArcturusB** [comment]
The JSON you’re posting appears to be invalid.

- Line 48 should end with a comma (`"startpage": "https://startpage.com/do/dsearch?query={}",`), 
- Line 59 should’t (`"*calendar.google.com/*"`).

Is should work if you correct the syntax. ;)

You can check your config with any JSON that’s available on the web before submitting it to vim-vixen.

**Comment by japhir** [comment]
Ah ofcourse! Thanks.

I just wasn't sure that it was actually trying to parse/save the file. Apparently it was, but found an error and went back to the default as a result.

**Comment by ueokande** [comment]
I recognize that current caution of validation in settings is not so user-friendly.  That will be fixed in the  future.  Thank you.

**Comment by dikti** [comment]
Would be great if you could provide a save-button either way, for the warm fuzzy feeling of pressing save myself. As a new user, I wondered if my edits are saved too, without knowing before looking back after closing the preferences.
