### ISSUE TITLE
partial blacklist: possibility to blacklist only certain buttons from a certain webpage

### ISSUE THREAD

**Issue by japhir** [ueokande/vim-vixen#144]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description

Currently, we can blacklist a whole webpage. It would be very nice if we could only disable certain keys for each webpage separately. In my case, I would like to disable some of the gmail/google calendar keybindings, but leave intact the ones that do not conflict. This would allow me to j/k through my email as usual, but still allow for tab-switching, tab closing, etc.

possible formatting for this could be along the lines of:
```
"blacklist": [
	"j,k": *mail.google.com/*",
	"j,k": *calendar.google.com/*"
]
```
but I'm sure this isn't valid JSON ;-).

**Comment by dmusican** [comment]
I'll add that I'd love to see this feature.

**Comment by HieuTranTH** [comment]
This feature is very much needed. Block the plugin is not enough since I still need to cycle through tabs with "J,K" or "gt,gT".

**Comment by ueokande** [comment]
Here is the proposal of the new blacklist syntax:
```json
"blacklist" [
    { "url": "amazon.com/*", "keys": ["j", "k"] },
    { "url": "mail.google.com/*", "keys": ["j", "k", "f"] },
    "github.com/*"
]
```
