### ISSUE TITLE
Cannot open bookmark by keyword

### ISSUE THREAD

**Issue by casperravenhorst** [ueokande/vim-vixen#145]
### I'm opening this issue because:

- [ ] I'll report a bug
- [X] I'll propose a new feature

### Description
In bookmark manager you can mark certain often-visited bookmarks with a keyword, eg. you have a page with production status reports and you put the 'status' keyword on the bookmark. Now in url bar of firefox you can type status and it will take you there, but not the same behaviour is seen for `:open` or `:tabopen`.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Make a bookmark with a keyword (this is not the same as a tag)
2. Close bookmark manager
3. In browser window press `t` to show `:tabopen`
4. Enter keyword and press `Enter`
5. Browser opens google with keyword, instead of bookmark url

#### System configuration

- Operating system: OSX
- Firefox version: 56.0.2
- Vim-Vixen version: 0.4

#### Console logs

Any relevant log in developer tools:
No

**Comment by dannycolin** [comment]
As a workaround, you can add an entry in the search engine list.

For example, I have "tw" pointing to "https://www.twitter.com/". So when I type : `:o tw` it opens Twitter.
