### ISSUE TITLE
Pressing f while searching triggers the follow-link keymap

### ISSUE THREAD

**Issue by svarogg** [ueokande/vim-vixen#151]
### I'm opening this issue because:

- [X] I'll report a bug
- [ ] I'll propose a new feature

#### Steps to Reproduce

1. Open some web page with links
2. Press / to open quickfind pop-up.
3. Type a search query that contains the letter 'f'.
4. See that follow-links was triggered.

#### System configuration

- Operating system: Windows 10 (Will most-probably be the same for any operating system)
- Firefox version: 56.0.2
- Vim-Vixen version: 0.4

**Comment by laurentbardin** [comment]
Unable to reproduce.

**System configuration**
 * Operating system: macOS 10.12.6
 * Firefox version: 57.0
 * vim-vixen version: 0.5

**Comment by omajid** [comment]
I am also unable to reproduce.

**Comment by svarogg** [comment]
Sorry about late re-appearence. Was a little busy.

Anyway, tested it now on FF57, and things seem to work correctly. So closing the ticket. 

Well done team! ;)
