### ISSUE TITLE
Display when vim-vixen is disable

### ISSUE THREAD

**Issue by ljoli** [ueokande/vim-vixen#155]
### I'm opening this issue because:

- [x] I'll propose a new feature

### Description
I would like add a feature present in vimperator.
When we disable plugin add a popup or something we can see clearly

#### System configuration

- Operating system: linux 
- Firefox version: 56.0
- Vim-Vixen version: 0.8

**Comment by bennypowers** [comment]
Agreed. since I need to disable VV on codepen, jsbin, etc, so I can use their keybindings, I'd like specific visual feedback that the plugin is disabled.

**Comment by ueokande** [comment]
One idea is the state is shown in toolbar, and users can toggle enable/disable by click it.
I expect that shown in bottom of the page like Vimperator constantly is not good idea, because that requires to insert a DOM and it may hide the elements in the page.
