### ISSUE TITLE
open / tab-open console gets slowing when query string is long

### ISSUE THREAD

**Issue by Biacco42** [ueokande/vim-vixen#158]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description

open / tab-open console gets slowing when query string is longer than 3 ~ 4 characters.
IME (Google Japanese Input) also slows down.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. hit "t" / "o" or ":tabopen" / ":open"
2. type some character
3. over 3 or more characters causes the issue

#### System configuration

- Operating system: Mac OS 10.12.6
- Firefox version: 57.0
- Vim-Vixen version: 0.5

#### Console logs

Any relevant log in developer tools:
N/A

**Comment by aureooms** [comment]
Culprit is [here](https://github.com/ueokande/vim-vixen/blob/7e506f5f212ce57362bb644c2c2d7a9f763282cb/src/background/histories.js#L64).

**Comment by aureooms** [comment]
It seems the only part actually depending on the keyword is the API call to `browser.history.search`, assuming longer keywords return less results. Looks difficult to do better. Maybe delaying the search while the user is typing would be a first fix (I do not see it done anywhere at the moment).

**Comment by aureooms** [comment]
I was wrong. There does seem to be [another place depending on the length of the keyword(s)](https://github.com/ueokande/vim-vixen/blob/7e506f5f212ce57362bb644c2c2d7a9f763282cb/src/shared/commands.js#L72).

**Comment by aureooms** [comment]
Ok that one only loops through the search engines from the configuration and should not be too slow.

**Comment by sukima** [comment]
It has been a year, Has there been any progress on this? It is really affecting the ability to type in the VimVixen console line. Without a fix in sight I'm close to dropping this addon. I did attempt to look at the source but the current abstractions in use are not making much sense. Is there some documentation on how that command line functions (Design Specs)?

**Comment by awu0012** [comment]
@sukima feel free to take a look at https://github.com/awu0012/vim-vixen/commit/c0fb340df2aa2b2af7cc1139f4745b25acca79c9

not a javascript programmer by any means, but it works for me

**Comment by ueokande** [comment]
I have started to use Vim Vixen on macOS recently, and I encounter the same issue. It might be a particular problem with macOS.   We need to research more on this issue.

**Comment by ueokande** [comment]
fixed in #1099
