### ISSUE TITLE
Feature-request: Add binding for going back to the most recently used tab

### ISSUE THREAD

**Issue by haadr** [ueokande/vim-vixen#164]
Until recently I used VimFX, which had a binding for going to the most recent tab. This is not the same as the current binding for going to the "prev tab" (which is the tab situated "before" the current tab in the tab list), but instead going back to the most recently viewed tab, which might be anywhere in the tabs list.

In vim I would do Ctrl+6 to go to the most recently viewed buffer. In VimFX this was gL. 

Thanks for creating a new future-proof vim addon for firefox!

**Comment by alx741** [comment]
This one is implemented in the #137  PR

**Comment by lydell** [comment]
>  In VimFX this was gL

I think you mean `gl`. `gL` selects the oldest unvisited tab.

https://github.com/akhodakivskiy/VimFx/blob/master/documentation/commands.md#gl

**Comment by ueokande** [comment]
merged in #137
