### ISSUE TITLE
enabling vim-vixen blanks https://postgresweekly.com/

### ISSUE THREAD

**Issue by bronsen** [ueokande/vim-vixen#170]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description
Opening https://postgresweekly.com/ on FF57 with vim-vixen enabled renders the page blank: it's just all white. However, pressing 'f' does hightlight a few spots, but I cannot see what I would select. Now, when I disable vim-vixen and reload that tab, I see the content as expected. Then, as soon as I re-enable vim-vixen, the page becomes white again.

I do have other extensions active, if needed I can provide all "Troubleshooting Information" from FF itself.

#### Steps to Reproduce

1. Have vim-vixen enabled
2. open https://postgresweekly.com/
3. (In my case I) see that the page is blank/white
4. Disable vim-vixen
5. Relead the page
6. (In my case I) see the expected page content.
7. Re-enable vim-vixen
8. The page is immediately rendered blank/white.

#### System configuration

- Operating system: ubuntu 16.04.3
- Firefox version: ff 57.0 64bit
- Vim-Vixen version: 0.5

#### Console logs
This error ("could not establish connection") appears after re-enabling the plugin and after the page has become all white
![2017-11-16-140347_1914x44_scrot](https://user-images.githubusercontent.com/170530/32892576-ff3a6ea4-cad6-11e7-82a3-0d0b9a3179bd.png)

**Comment by ueokande** [comment]
#160 can close this this issue.
