### ISSUE TITLE
Ability to change the colors and font

### ISSUE THREAD

**Issue by alabrand** [ueokande/vim-vixen#176]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description

Perhaps see if it's possible for users to modify the colors and fonts of vim-vixen. If this is implemented then it's important to also document all the things one can change, either on GitHub or in the about:addons settings page.

**Comment by ueokande** [comment]
discuss in #161

**Comment by tjkirch** [comment]
#161 is just about the colors and font in the console, whereas I thought this issue was about colors and font everywhere.  For me, the hints are the most important; I often can't read them.  I don't see an open issue about hint styling.

**Comment by vloaix** [comment]
I second it. It would be nice to be able to customize hint styles.
