### ISSUE TITLE
Can't open about:config and about:addons

### ISSUE THREAD

**Issue by alabrand** [ueokande/vim-vixen#179]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description

vim-vixen is unable to open about:config and about:addons, but it can open about:home.

#### Steps to Reproduce

1. Install vim-vixen
2. Open up the console with `:`
3. Type `:o about:config` or `:t about:addons`

#### System configuration

- Windows 10 Pro 64-bit
- Firefox Nightly 59.0a1 64-bit
- vim-vixen 0.5

**Comment by ueokande** [comment]
duplicated with #106
