### ISSUE TITLE
Blocks standard keybinding - does not provide an alternative.

### ISSUE THREAD

**Issue by xircon** [ueokande/vim-vixen#181]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description
Default configuration blocks a standard key binding - ctrl+d to bookmark:
```
"<C-D>": { "type": "scroll.pages", "count": 1 },
```
### Failure Information (for bugs)
Does not provide an alternative keybinding.

#### Steps to Reproduce
Press Ctrl+D 

Please provide detailed steps for reproducing the issue.
N/A

#### System configuration

- Operating system:
Manjaro X64
- Firefox version:
Nightly
- Vim-Vixen version:
0.5
#### Console logs
N/a

Any relevant log in developer tools:
N/a

**Comment by sprnza** [comment]
Is there a way to disable the default shortcut? I'd like to use C-D for bookmarking

**Comment by AlexeySachkov** [comment]
@sprnza, just update plugin configuration file at `about:addons` page: you need to remove (or change the keys) `"<C-D>": { "type": "scroll.pages", "count": 0.5 },` line from json config file

**Comment by sprnza** [comment]
@AlexeySachkov Yep, thank you!
