### ISSUE TITLE
Bind JavaScript code for key

### ISSUE THREAD

**Issue by jkeks** [ueokande/vim-vixen#185]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description
Need to run JavaScript code by pressing keys

#### Steps to Reproduce
press key e
show alert("EEee!");

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

#### System configuration

- Operating system:
- Firefox version:
- Vim-Vixen version:

#### Console logs

Any relevant log in developer tools:

**Comment by ueokande** [comment]
duplicated #146
