### ISSUE TITLE
Show Bookmarks in :open and :tabopen

### ISSUE THREAD

**Issue by Lorur** [ueokande/vim-vixen#186]
### I'm opening this issue because:

- [ ] I'll report a bug
- [X] I'll propose a new feature

### Description

Coming from VimFx, I used the _eb_ command to gain access the firefox menues. Then I opened the bookmark folder using the shown key combination.

Due to limitations of the API, this behavior seems to be impossible to reproduce right now. As a quick workaround, I propose a feature that reads my bookmarks and shows it in the Vim Vixen Command. Selecting them should open the bookmarked page.

Story 1:

1. Open Vim Vixen Command
2. type :open vim
3. show all bookmark containing the the word _vim_ next to/under/over the search engines
4. User can navigate between bookmarks and choose the one he wants to be opened

Story 2:
1. Open Vim Vixen Command
2. type :open google
3. if the user has a bookmark containing _google_, he should see it, but the focus is on the search engine modifier keyword

**Comment by chocolateboy** [comment]
https://github.com/ueokande/vim-vixen/issues/145

**Comment by ueokande** [comment]
duplicated
