### ISSUE TITLE
Blacklisting localhost

### ISSUE THREAD

**Issue by caneta** [ueokande/vim-vixen#187]
### I'm opening this issue because:
I'll report a bug

### Description
Vim Vixen does not blacklist localhost

#### Steps to Reproduce
Configuration:
```
"blacklist": [
  "localhost"
]
```
Go for example to `http://localhost:8080/`, press `f` and the vim vixen link letters appear

#### System configuration

- Operating system: Linux Xubuntu 12.04
- Firefox version: 57
- Vim-Vixen version: latest

**Comment by ueokande** [comment]
`localhost` must not block `localhost:8080`, because of different URL origin.  You can use `localhost:*`
