### ISSUE TITLE
Console dos not show on webseite with restrective CSP Policy

### ISSUE THREAD

**Issue by Akasch** [ueokande/vim-vixen#189]
### I'm opening this issue because:

- [ x] I'll report a bug
- [ ] I'll propose a new feature

### Description

If a website has a restrictive style Contend-Security-Policy (CSP) which does not allow inline styles the console is not formatted correctly. Additionally CSP Reports are potentially send to the reporting URL of the Policy

### Failure Information (for bugs)

The console appears to work, but is not shown on screen and therefore appears not working.

#### Steps to Reproduce

1. Open site with CSP Policy (for example https://bitpoll.mafiasi.de)
2. try to open a tab via o
3. console is not shown
4. Scroll to the button of the page
5. notice the console is permanently there

#### System configuration

- Operating system: Debian buster/sid
- Firefox version: 57.0 (64-bit)
- Vim-Vixen version: 0.5

#### Console logs

Any relevant log in developer tools:

Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src https://bitpoll.mafiasi.de”).
bitpoll.mafiasi.de:1
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src https://bitpoll.mafiasi.de”). Source: .vimvixen-console-frame {
  margin: 0;
 ....
bitpoll.mafiasi.de:1
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src https://bitpoll.mafiasi.de”).
bitpoll.mafiasi.de:1
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src https://bitpoll.mafiasi.de”). Source: .vimvixen-hint {
  background-color: yel....
bitpoll.mafiasi.de:1

**Comment by bovine3dom** [comment]
This is a Firefox bug that they are fixing: https://blog.mozilla.org/addons/2017/11/20/extensions-in-firefox-58/ & https://bugzilla.mozilla.org/show_bug.cgi?id=1267027

**Comment by Marwes** [comment]
No idea if it helps but this was posted as a possible alternative on the firefox bug https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contentScripts
