### ISSUE TITLE
request: gu to navigate to parent url path

### ISSUE THREAD

**Issue by nachoparker** [ueokande/vim-vixen#192]
it is very nice to do `gu` in vimperator and go back to the parent path, for instance

https://github.com/ueokande/vim-vixen/issues -> https://github.com/ueokande/vim-vixen/

please, consider it for the future!

thanks and good job

**Comment by chocolateboy** [comment]
It's already implemented:

    "gu": { "type": "navigate.parent" },

**Comment by nachoparker** [comment]
:S sorry, I think I must have tried it in an addon page or something like that

keep the good job
