### ISSUE TITLE
navigating to next and previous links in posts

### ISSUE THREAD

**Issue by nachoparker** [ueokande/vim-vixen#193]
hi again,

a very neat feature of vimperator was the ability to do ]] and [[ and if the website has a next, previous (for instance, a multi page post, or a listing) it will follow the links.

That would be great, thanks again for your good job!

**Comment by a13xmt** [comment]
Seems like this is already implemented. The corresponding methods are:
```
"[[": { "type": "navigate.link.prev" },
"]]": { "type": "navigate.link.next" },
```

**Comment by nachoparker** [comment]
oh sorry, I tried it and I thought it didn't work
