### ISSUE TITLE
Focusing on inner scrollbox on page

### ISSUE THREAD

**Issue by huffstler** [ueokande/vim-vixen#194]
### I'm opening this issue because:

- [x] I'll propose a new feature

### Description

I think it'd be pretty nifty to be able to select an area with an inner scroll box (most commonly code on stackoverflow) and scroll through with the hjkl keys. As of right now, there's no way (that I know of) to give focus to that inner scrollbox.

### System configuration

- Operating system: Windows 7 64 bit
- Firefox version: Firefox Nightly 59.0a1 2017-11-17 64 bit
- Vim-Vixen version: 0.5

**Comment by ueokande** [comment]
duplicated #81
