### ISSUE TITLE
follow-start option: add background tabs

### ISSUE THREAD

**Issue by cosimone64** [ueokande/vim-vixen#197]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description
The extension I was using before upgrading to Firefox 57, VimFx, had a simple, yet very desirable option to open links in **background** tabs instead of opening them in a new tab and changing to it through F+label.
It would be great to have some way to do it too in Vim Vixen.

#### Steps to Reproduce
A simple "background-tab" boolean variable, or changing "new-tab" to an integer variable in the JSON configuration file should suffice. I would personally  suggest the latter approach.

1. step 1
Substitute the "new-tab" variable with an integer (or a string) variable that can take three values (example):
0: link will be opened in the current tab;
1: link will be opened in a new **foreground** tab;
2: link will be opened in a new **background** tab.

2. you get it...

#### System configuration

- Operating system: Arch Linux, running Linux Kernel 4.13.12-1-ARCH
- Firefox version: 57.0
- Vim-Vixen version: 0.5

**Comment by a13xmt** [comment]
Thanks for the detailed write up. This feature is already in progress #60 #62.

**Comment by ueokande** [comment]
duplicated  #60
