### ISSUE TITLE
Support syncing preferences with firefox sync

### ISSUE THREAD

**Issue by swalladge** [ueokande/vim-vixen#199]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description

The settings for vim-vixen should support being synced across firefox sync. Otherwise I need to manually copy config changes to each computer I wish to use it with.

**Comment by chen-chao** [comment]
Could this be achieved by changing all `storage.local` to `storage.sync`?

**Comment by ueokande** [comment]
@chen-chao maybe

**Comment by chen-chao** [comment]
@ueokande I've tested storage.sync and it seems ok for me.

**Comment by ueokande** [comment]
The firefox sync enabled version has been released!
