### ISSUE TITLE
Incompatibility when viewing certain website - a grey screen is displayed blocking the webpage

### ISSUE THREAD

**Issue by lohithbb** [ueokande/vim-vixen#209]
### I'm opening this issue because:

- [x] I'll report a bug

### Description

When browsing to certain pages, for example, the [graze](https://www.graze.com/) website, a grey screen loads. Clicking randomly on the page seems to navigate to the content underneath the (opaque) grey layer.

_This might be related to #208?_

### Failure Information (for bugs)

See the section below on how to reproduce. I'm not a HTML guru so I'm not sure what is even going wrong under the hood.

#### Steps to Reproduce

1. Install Vim Vixen on the new Firefox Quantum.
2. Browse to the [graze](https://www.graze.com) website.
3. You should notice the website load/render partially before being entirely greyed out.
4. (Optional) Pressing "f", highlights the links on the page - so the webpage loaded fine and the links were highlighted correctly.
5. Disabling the add-on allows it to load normally.

#### System configuration

- Operating system: Windows 10 Home
- Firefox version: 57.0 (64-bit)
- Vim-Vixen version: 0.5

**Comment by ueokande** [comment]
@lohithbb Resolved in #127, included in next release!
