### ISSUE TITLE
Slow response in console (open/tabopen/etc.) as you search

### ISSUE THREAD

**Issue by jinyeow** [ueokande/vim-vixen#214]
### I'm opening this issue because:

- [X] I'll report a bug

### Description
The console open/tabopen/etc. slows down quite noticeably after typing more than a few characters.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. press 'o' or 't'
2. type 'vim-vixen issues'
3. notice the lag as you type '-vixen issues'

**Comment by ueokande** [comment]
duplicated #158
