### ISSUE TITLE
Command bar not correctly visible if URL text is shown

### ISSUE THREAD

**Issue by shahvah** [ueokande/vim-vixen#215]
### I'm opening this issue because:
- [x] I'll report a bug

### Description
If there is something shown at the bottom of Firefox window, such as "the URL of the hovering mouse link", the command bar is not visible correctly anymore.

### Failure Information (for bugs)
At least the begenning of the command bar, if not all, is not visible because of this issue. So you don't get to see what you are typing. Either the command bar should come on top or it should be drawn _higher_ than the usual bottom place.

#### Steps to Reproduce
1. Have your mouse hovered on any link.
2. Make sure that Firefox is indeed showing the URL of the link at the bottom corner.
3. Type ":" or "t", etc. to have the command bar visible.
4. You will find that the "URL" is masking the command bar.

#### System configuration
- Operating system: GNU/Linux (64)
- Firefox version: 57.0 (64-bit)
- Vim-Vixen version: 0.6

#### Console logs
N.A.

**Comment by ueokande** [comment]
duplicate  #203
