### ISSUE TITLE
"about:config" considered as illegal URL

### ISSUE THREAD

**Issue by shahvah** [ueokande/vim-vixen#217]
### I'm opening this issue because:
- [x] I'll report a bug

### Description
It is not possible to open the addon-manager page through the new tab/window commands.

### Failure Information (for bugs)
If you type anything with ":", it is considered as _Illegal URL_. This is true for _about:addons_, _about:config_, and the likes.

#### Steps to Reproduce
1. Type __t__/__w__, so that the _tabopen_/_winopen_ commands are in action
2. Fill in: __about:config__
3. You will get _Illegal URL_ error message.

#### System configuration
- Operating system: GNU/Linux (64-bit)
- Firefox version: 57.0 (64-bit)
- Vim-Vixen version: 0.6

#### Console logs
N.A.

**Comment by ueokande** [comment]
duplicate  #106
