### ISSUE TITLE
Next item keybinding in console conflicts with new window 

### ISSUE THREAD

**Issue by mdsib** [ueokande/vim-vixen#223]
### I'm opening this issue because:

- [x] I'll report a bug
- [x] I'll propose a new feature

### Description
Currently, the hard-coded keybinding for next item in the console conflicts with Firefox's new window keybinding. See https://github.com/ueokande/vim-vixen/blob/507c5b4f78aee09b45182f2b2650c61b11b68950/src/console/components/console.js#L77

One option would be to disable Firefox's `<C-N>` keybinding, if possible.

Another option would be to allow users to customize this keybinding to get it off of `<C-N>`, which would be nice for people who want to use arrow keys. A temporary fix could involve adding the additional up/down arrow keys to the list of keycode checks.

#### Steps to Reproduce

1.Type `:buffer `.
2. Press `<C-P>` a few times and see the highlighted buffer entry.
3. Press `<C-N>` and notice that a new window has opened, instead of the intended action: next item on buffer entry list is highlighted.

#### System configuration

- Operating system: Linux version 4.13.12-1-ARCH (64 bit)
- Firefox version: 58.0b3
- Vim-Vixen version: 0.6

**Comment by ueokande** [comment]
duplicated #200
