### ISSUE TITLE
Find bar is sometimes hidden behind popup URL/status at bottom of screen

### ISSUE THREAD

**Issue by dmusican** [ueokande/vim-vixen#226]
### I'm opening this issue because:

- [X] I'll report a bug
- [ ] I'll propose a new feature

### Description

Firefox has a small popup at the bottom left of the screen that's a URL when the mouse is hovering over a link, and it's a status when a page is loading. If you hit the "/" for finding text within a page because that popup is there, the box where you type in text for finding things isn't visible because it's hidden behind that small popup.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Put mouse on top of a link. so you can see the popup at the bottom.
2. Press "/" to search.
3. Observe that you can't see any search box appear.

#### System configuration

- Operating system: Ubuntu 16.04
- Firefox version: 57.0
- Vim-Vixen version: 0.6

**Comment by ueokande** [comment]
duplicate  #203
