### ISSUE TITLE
Bug: Searching tabs in buffer doesn't work

### ISSUE THREAD

**Issue by bad63r** [ueokande/vim-vixen#227]
### I'm opening this issue because:

- [* ] I'll report a bug
- [ ] I'll propose a new feature

### Description
Filtering/searching tabs in the buffer (default key "b") seems not to work properly.

#### Steps to Reproduce
Open 3 tabs: 1) https://github.com/ueokande/vim-vixen  2) https://duckduckgo.com/?q=Test&atb=v38-1&ia=web  3) http://www.omgubuntu.co.uk/ 
Press "b" and type "test" . There is no tab to select. It should be tab number 2.
  

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

#### System configuration

- Operating system: Ubuntu 16.04
- Firefox version: 57
- Vim-Vixen version: 0.6

#### Console logs

Any relevant log in developer tools:

**Comment by ueokande** [comment]
Because buffer command is currently case sensitive.  I'll close this, and we got to continue discussion in #125.
