### ISSUE TITLE
Request :split :vsplit (tile type window manager)

### ISSUE THREAD

**Issue by harupiyo** [ueokande/vim-vixen#231]
### I'm opening this issue because:

- [ ] I'll propose a new feature

### Description

I love "Tile typed window manager" on vim.
Because we usually use wide screen like a milti screen. 
Or sometime, I look head and tail over a single page.

Thanks.

Vim の画面分割機能を愛用していますので、欲しいです。
（なぜかVimperator では実現されなかった機能です。）
Vim 野郎であれば息をするがごとく自然に行っていると思うのですが、同じページの上部と下部を眺めるために使ったり、複数ドキュメントを並列に比較したりするなどの応用につながります。
また今のPCのスクリーンは横長のものが多いので、縦長のWeb ページの一枚を表示するにはもったいないですよね。Windows の画面分割でFirefox の２つのウィンドウを左右に配置することで凌いでいますが、機能として実装していただければこれほど嬉しいことはありません。
読んでいただき、ありがとうございました。
愛好者より。

**Comment by grummi92** [comment]
Firefox does not seem to support viewing the same page in multiple tabs.
There were several addons that did tiling of tabs, to show multiple tabs in a single window at the same tabs, but they don't work anymore with Firefox 57.

There is a new Extension that emulates this behaviour by simulating tabs with different windows (https://addons.mozilla.org/en-US/firefox/addon/tile-tabs-we/).

I can't imagine that Vim Vixen will implement this behaviour until Firefox implements an API for it.

**Comment by harupiyo** [comment]
I understood very well that the situation is very difficult.
Thanks your kindfull description for me.

**Comment by grummi92** [comment]
Please understand that I am not a developer nor in any way can speek for the developer, the above is just my own estimation. ueokande may decide to implement it after all, it just seems to me that at least for now it is very unlikely. :-)

**Comment by harupiyo** [comment]
okay, I understand.
Thanks.
