### ISSUE TITLE
Can not follow links on some pages

### ISSUE THREAD

**Issue by omajid** [ueokande/vim-vixen#234]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description

I can't follow links on some web pages.

For example, if I go to this web page: 
https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-conditions

I can't find a way to use vim-vixen to open the "Visual Studio Project/Item Template Parameter Logic" link (in the center of the page).

It looks like the key to open that link is `a`, but `aa` is used to open links in the tree on the left. I can't find a way to follow that link. Here is a screenshot of what it looks like on my end:
  
![image](https://user-images.githubusercontent.com/174451/33141691-e909b414-cf81-11e7-8d41-95e702fb91c9.png)

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Go to https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-conditions
2. Enter `f` to open a link
3. Hit `a` to follow the "Visual Studio Project/Item Template Parameter Logic" link but nothing happens.

#### System configuration

- Operating system: Fedora 27
- Firefox version: 57
- Vim-Vixen version: 0.6

#### Console logs

Any relevant log in developer tools:

**Comment by ueokande** [comment]
Press <kbd>Enter</kbd>

**Comment by omajid** [comment]
Thanks!

 Please consider changing this to be more "obvious". I have never had to press enter so far for following links (not in vimperator, nor in vim-vixen), so expecting users to know this corner case seems very un-obvious. Perhaps you can use some other set of keys that are not shared with other link items?

**Comment by PolyMMA** [comment]
Same issue here but when pressing Enter the hints just disappear and the A-link is never followed...

Vim Vixen
Version 0.32
Last Updated December 29, 2020

Mozilla Firefox 84.0 (64-bit) for Ubuntu canonical -1.0

Distro: Ubuntu 18.04.5 LTS
Kernel: 4.15.0-128-generic x86_64 
bits: 64 
Desktop: Xfce 4.14.2 (Gtk 3.22.30) 
info: xfce4-panel 
dm: lightdm
