### ISSUE TITLE
Can't scroll down on this webpage...

### ISSUE THREAD

**Issue by ghost** [ueokande/vim-vixen#235]
### I'm opening this issue because:

- [X] I'll report a bug
- [ ] I'll propose a new feature

### Description

On some web pages I cannot scroll down e.g. https://www.usbeketrica.com

### Failure Information (for bugs)

Cannot scroll the page, but following links work.

#### System configuration

- Firefox version: Quantum
- Vim-Vixen version: latest

**Comment by Tahvok** [comment]
I have a scroll up issue on some other pages too
