### ISSUE TITLE
Add :help to display key bindings

### ISSUE THREAD

**Issue by valvin1** [ueokande/vim-vixen#239]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description

I'm newbie with this extension and stay on github Readme to check key bindings. It would be nice to have a `:help` command to browse it.

#### System configuration

- Operating system: Linux Xubuntu 16.04
- Firefox version: 58.0b5
- Vim-Vixen version: 0.6

**Comment by dannycolin** [comment]
Would be great so when there's new function added we don't need to go on github everytime we want to learn them :)

**Comment by rNoz** [comment]
Exactly. The same thing happens to each newcomer.

**Comment by sigboe** [comment]
Please
