### ISSUE TITLE
Everything starting from a '#' character when opening a page is ignored

### ISSUE THREAD

**Issue by omajid** [ueokande/vim-vixen#244]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description

When I start a search that includes the `#` character, I can enter a long search phrase but everything  after `#` character is ignored.

#### Steps to Reproduce

1. `t C# tutorial`

In my case it opens google but it apparently searched for just "C" rather than "C# tutorial". 

While typing, the "instant" results shown (based on history?) apparently include the `#` character. But the actual search string doesn't.

#### System configuration

- Operating system: Fedora 27 x86_64
- Firefox version: 57
- Vim-Vixen version: 0.6

#### Console logs

Any relevant log in developer tools:

**Comment by ueokande** [comment]
fixed

**Comment by omajid** [comment]
Thanks!
