### ISSUE TITLE
Selectively enable/disable binds on blacklisted sites.

### ISSUE THREAD

**Issue by gbpi** [ueokande/vim-vixen#245]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description

Some sites already have nice keybindings, DuckDuckGo for example uses jk to select a result, l to follow the link and h to return to the top. I can blacklist that site and use their built in binds, but then I can't switch tabs with JK. It would be nice to have some options in the blacklist to only disable the keybinds that interfere on that site.

**Comment by ueokande** [comment]
duplicate #144
