### ISSUE TITLE
google search in command line replaces + with whitespace

### ISSUE THREAD

**Issue by zepto88** [ueokande/vim-vixen#256]
### I'm opening this issue because:

- [X] I'll report a bug
- [ ] I'll propose a new feature

### Description
google search in command line replaces '+' with whitespace

#### Steps to Reproduce
1. press o
2. type for example "c++" or "google c++"
3. search has now replaced "c++" with "c  "

#### System configuration

- Operating system: Ubuntu 16.04, Windows 8.1
- Firefox version: 57.0
- Vim-Vixen version: 0.6

#### Console logs

Any relevant log in developer tools:

**Comment by ueokande** [comment]
fixed in #252
