### ISSUE TITLE
Issues with tvtropes.org

### ISSUE THREAD

**Issue by QuDu43bChhiONNVlgkoy** [ueokande/vim-vixen#257]
### I'm opening this issue because:

- [X] I'll report a bug
- [ ] I'll propose a new feature

### Description
Having trouble with folders. For example, http://tvtropes.org/pmwiki/pmwiki.php/Series/StarTrekTheNextGeneration. Here, if I go into link following mode I don't get any option to open the folder. Other vim addons like vimium support this.
#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Go to a page with folders (Example, http://tvtropes.org/pmwiki/pmwiki.php/Series/StarTrekTheNextGeneration)
2. Scroll down to the folders.
3. Press [f]

#### System configuration

- Operating system: Windows 10
- Firefox version: 57
- Vim-Vixen version: 0.6

**Comment by grummi92** [comment]
These folders are `div` elements. Unlike #241 these elements have an `onclick` attribute.

I think elements with onclick should also be included with the link following functionality.

Vimperator uses the following XPath to determine which elements should be included (found in common/share/hints.js):
```        const DEFAULT_HINTTAGS =
            util.makeXPath(["input[not(@type='hidden' or @disabled)]", "a", "area", "iframe", "textarea", "button", "select"])
                + " | //*[@onclick or @onmouseover or @onmousedown or @onmouseup or @oncommand or @role='link'or @role='button' or @role='checkbox' or @role='combobox' or @role='listbox' or @role='listitem' or @role='menuitem' or @role='menuitemcheckbox' or @role='menuitemradio' or @role='option' or @role='radio' or @role='scrollbar' or @role='slider' or @role='spinbutton' or @role='tab' or @role='textbox' or @role='treeitem' or @tabindex]"
                + (config.name == "Muttator" ?
                    " | //xhtml:div[@class='wrappedsender']/xhtml:div[contains(@class,'link')]" :
                    "");
```
