### ISSUE TITLE
GUI settings

### ISSUE THREAD

**Issue by ueokande** [ueokande/vim-vixen#26]
### I'm opening this issue because:

- [ ] I'll report a bug
- [X] I'll propose a new feature

### Description

Provide a GUI for settings

**Comment by ueokande** [comment]
Is this what the customer really needed...?
![dlr7d6vwkaad_pd jpg large](https://user-images.githubusercontent.com/534166/32103220-66e6ab12-bb5a-11e7-8045-93fc238793d7.jpeg)

**Comment by ainola** [comment]
It might be better from a UX perspective to have the operation hard-coded on the left and the key box on the right. The operations shouldn't need to be selected by the user, they should already just be there. The "Key" value could capture user input to map quickly and easily. However, this method would mean that a secondary key mapping would not be possible without having something like an "Alternative Key Mapping" box as well.

**Comment by ueokande** [comment]
> It might be better from a UX perspective to have the operation hard-coded on the left and the key box on the right.

That's great and I agree that.
I expect the GUI setting is needed by beginners, so unavailable alternative keys is not a problem. That UI cannot also provide to change an amount of scroll, but it's OK because of the above reason. Such user must be able set by JSON.

**Comment by johannesschweig** [comment]
It would be also great to have an error feedback when changing the json. Trying to alter search engines and it is hard to guess what is keeping the add-on from accepting the change.

**Comment by ueokande** [comment]
It is a draft.
![draft](https://user-images.githubusercontent.com/534166/33130521-fafa2af0-cfd6-11e7-827e-d80d0f35cb5f.png)

**Comment by ainola** [comment]
Looks great!

**Comment by ueokande** [comment]
current progress...
![gui](https://user-images.githubusercontent.com/534166/33237000-8312dffc-d2a9-11e7-9d2e-609e3d7cbc1e.png)
