### ISSUE TITLE
Tab Search

### ISSUE THREAD

**Issue by andre-cunha** [ueokande/vim-vixen#261]
### I'm opening this issue because:

- [ ] I'll report a bug
- [ X ] I'll propose a new feature

### Description
Tab search. Shift + T provides a search tab feature.
Look for key words on tab's title, and once selected open the tab.

**Comment by AnomalRoil** [comment]
I'm struggling to see the difference with the buffer `b` feature?

**Comment by andre-cunha** [comment]
You are right. I didn't check the buffer function. Thanks for the response.
