### ISSUE TITLE
Add keybinding to go to startpage

### ISSUE THREAD

**Issue by thomascarreau** [ueokande/vim-vixen#262]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description

I just discovered your extension and it has all features I need expect the key binding `gh` to go to my startpage. I was really used to it with Vimperator and I think it could be nice to have this feature with vim-vixen. I think that is not a difficult task but I can't do it by myself since I am not familiar with JSON.

#### System configuration

- Operating system: Windows 7/Debian 9/Ubuntu 16.04
- Firefox version: 57.0
- Vim-Vixen version: 0.7

**Comment by ueokande** [comment]
memo:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings/homepageOverride
