### ISSUE TITLE
H/J to scroll does not work in gmail

### ISSUE THREAD

**Issue by robehickman** [ueokande/vim-vixen#267]
### I'm opening this issue because:

- [- ] I'll report a bug
- [ ] I'll propose a new feature

Using H or J to scroll up or down does not work in Gmail, it scrolls the outer browser frame instead of the email listing. There does not seem to be any way of focusing the mail listing, hovering the mouse over it or clicking on it does not help.

**Comment by singletS** [comment]
H/J doesn't seem to work for scrolling in google groups either (up/down arrows work, though).

**Comment by robehickman** [comment]
Browser extensions should get key events before they go anywhere near web scripts. Websites should not be able to mess up extension functionality.

**Comment by mike3run** [comment]
Thats exactly why, whoever comes last wins, they overwrite functionality. Try hitting `j` on a youtube video

**Comment by robehickman** [comment]
Extensions need to be able to get these events before they are sent to pages, with a pass-through mode. Without that facility things are going to be very fragile.

**Comment by elmerehbi** [comment]
So maybe the ability to disable on some websites that are keyboard-friendly (e.g. Inbox, Youtube)?
