### ISSUE TITLE
Increase horisontal padding on follow link hints

### ISSUE THREAD

**Issue by robehickman** [ueokande/vim-vixen#268]
### I'm opening this issue because:

- [- ] I'll report a bug
- [ ] I'll propose a new feature

### Description

Minor styling issue, the hints displayed with 'F' have plenty of padding at the top-bottom but little (1px?) at the left or right, a bit more padding would make it easier to read in my opinion.

Also, the current font , (at least on ubuntu 16.4 lts) the difference between 'I' and 'L' isn't immediately obvious at a glance. L has a vertical and bottom line while 'I' is just a vertical line. They are easy to distinguish now I'm aware of it but not on first impression. These character ambiguities are less of a problem in natural language.

**Comment by ueokande** [comment]
discuss in #161
