### ISSUE TITLE
Console Frame Showing on Websites (e.g. crates.io)

### ISSUE THREAD

**Issue by BrainBlasted** [ueokande/vim-vixen#270]
### I'm opening this issue because:

- [x] I'll report a bug

### Description

Vim-vixen's  console frame is appearing at the top of [crates.io](crates.io). 

**Screenshot:**
![Screenshot](https://i.imgur.com/sgRd9tw.png)
### System configuration

- **Operating system**: Arch Linux
- **Firefox version**: 58.0b8
- **Vim-Vixen version**: 0.7

**Comment by BrainBlasted** [comment]
This also occurs on Windows 10, Firefox 57.0.4

**Comment by ueokande** [comment]
caused by Content Security Policy. duplicated #189
