### ISSUE TITLE
add `Ctrl-[` alternative to `Esc`

### ISSUE THREAD

**Issue by deadc0de6** [ueokande/vim-vixen#273]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description

Please add `Ctrl-[` as an alternative to using `Escape`.

**Comment by idlewan** [comment]
It would be even better to be able to configure the key (like it was possible with VimFx).
I use `ctrl-[`, but also `ctrl-;` which is even faster and more comfortable. In any case, `ctrl-[` should be supported.

**Comment by ueokande** [comment]
duplicated #184
