### ISSUE TITLE
Is there away to have VimVixen disabled by default for new tabs?

### ISSUE THREAD

**Issue by kfili** [ueokande/vim-vixen#275]
Not sure if this is a good question to ask here but I'd like to use VimVixen when I opt too. At the moment with it enabled by default for every tab it gets in the way. I have always used classic keyboard shortcuts for websites and, for example I press 'D', the tab closes and i loose my work.

**Comment by nulldle** [comment]
In the VimVixen preferences blacklist all websites:
"blacklist": [
  "*"
]

**Comment by nulldle** [comment]
In the VimVixen preferences blacklist all websites:
```
"blacklist": [
  "*"
]
```

**Comment by vividn** [comment]
This solution doesn't work. You are unable to enable VimVixen at all on blacklisted sites, so this effectively prevents you from using the extension anywhere

**Comment by ueokande** [comment]
@vividn 
Oh, that is a bug occured on 0.25.  Thank you for your reporting.

On 0.24, you can enable by <kbd>Shift</kbd>+<kbd>Esc</kbd> at blacklisted site, but 0.25 not.  I'd address the problem, and fix it on the next version.

**Comment by vividn** [comment]
Ah I see, thanks for the quick response. Looking forward to the next release 🙂

**Comment by ueokande** [comment]
@vividn 
The fixed version 0.26 has been released.  Try it!
