### ISSUE TITLE
Jump Marks

### ISSUE THREAD

**Issue by grummi92** [ueokande/vim-vixen#276]
### I'm opening this issue because:

- [x] I'll propose a new feature

### Description

I'd like to have jump marks for jumping to specific positions on a page or to a specific position on a different tab, similar to vim.

Press `m{0-9a-z}` to set a local mark for the current tab, and `m{A-Z}` to set a global mark.
Press `'{0-9a-z}` to jump to this mark on the current tab, and `'{A-Z}` to switch to the tab where this global mark has been set.

**Comment by tjkirch** [comment]
I didn't realize how much I relied on this feature until it was gone!

**Comment by jstetten** [comment]
They're extremely important for this user.
