### ISSUE TITLE
hint key

### ISSUE THREAD

**Issue by ralpheeee88** [ueokande/vim-vixen#278]
with hints is there anyway to setup so that only certain letters/row on the keyboard is used...at the moment its all over the place which is quite annoying and surely it would be more ergonomic to limit these to a keyboard row...

### I'm opening this issue because:

- [ ] I'll report a bug
- [ ] I'll propose a new feature

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

#### System configuration

- Operating system:arch
- Firefox version:57.0.2
- Vim-Vixen version:0.7

#### Console logs

Any relevant log in developer tools:

**Comment by SamCB** [comment]
The Hit-A-Hint plugin for chrome has an option to limit the keys to a custom list. It's useful cause I just selected all the keys under my left hand. I assume this could be done as a sub-setting for the follow keymap?

```js
{
  "keymaps": {
    "f": { "type": "follow.start", "newTab": false, "keys": "qwerasdfzxcv" },
    "F": { "type": "follow.start", "newTab": true, "keys": "qwerasdfzxcv" },
    // ...
  },
  // ...
}
```

**Comment by ueokande** [comment]
configurable hint keys is comming on next release (#306)
