### ISSUE TITLE
Shortcut to View Page Source

### ISSUE THREAD

**Issue by tannakartikey** [ueokande/vim-vixen#279]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description
Shortcut for View Page Source

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

#### System configuration

- Operating system:
- Firefox version:
- Vim-Vixen version:

#### Console logs

Any relevant log in developer tools:

**Comment by ueokande** [comment]
`gf` in Vimperator
