### ISSUE TITLE
Add option to not switching to new tab with follow.start

### ISSUE THREAD

**Issue by deadc0de6** [ueokande/vim-vixen#282]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description

When opening link with `F`, would it be possible to add an option that specifies if FF switches to it or not. Currently `F` will directly switch to the opened tab which might not be always the expected behavior.

Something like this:
```
...
    "F": { "type": "follow.start", "newTab": true, "switch": false },
...
```

**Comment by ueokande** [comment]
duplicated  #60
