### ISSUE TITLE
Link opened in new tab should become child tab in Tree Style Tab

### ISSUE THREAD

**Issue by kopp** [ueokande/vim-vixen#284]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description

When opening a link in a new tab, this should become a child tab in
[Tree Style Tab](http://piro.sakura.ne.jp/xul/_treestyletab.html.en).
In my current situation, when I middle-mouse-click on a link, it opens that in a new tab and it gets correctly added as a child-tab in Tree Style Tab.
When I open the link using Vim-Vixen via `F a` (for example), it gets opened in a new tab, but which is a tab on the same level in Tree Style Tab.

### System configuration

- Operating system: (Arch) Linux 4.14
- Firefox version: 57.0.2 (64 bit)
- Vim-Vixen version: 0.7 (November 28th 2017)
- Tree Style Tab version: December 12th 2017

**Comment by AlexeySachkov** [comment]
Hi, the same issue you can reproduce on the following system:
* OS: Windows 10
* Firefox: 57.0.2 (32-bit)
* Vim-Vixen version: 0.7 (December 15, 2017)
* Tree Style Tab version: 2.4.3 (December 15, 2017)

**Comment by Luxoboy** [comment]
Hey,
Same with this configuration:

* Ubuntu 16.04
* Firefox 58.0.1
* Vim-Vixen 0.11 (signed version)
* Tree Style Tab 2.4.16

**Comment by david-me** [comment]
This issue is closed but it doesn't seem to be fixed for me

- Arch
- Mozilla Firefox 62.0
- Vixen 0.15
- Tree Style Tab 2.4.24

**Comment by hukka** [comment]
It seems to be working when I just upgraded to Vixen 0.15 and Tree Style Tab 2.4.24 on Firefox 61. If there's an issue with Firefox 62, or the issue simply is still occuring for some people, I recommend you reopen the issue to make it more visible.

**Comment by david-me** [comment]
You're right. I realized the problem only happens when I also have the [Conex](https://addons.mozilla.org/en-US/firefox/addon/conex/?src=search)  extension (which does containers)  enabled. I'll open a new issue

**Comment by kopp** [comment]
@hukka : I have the same versions/settings as you, and it mostly works: Opening a link on e.g. github in a new tab makes it a child of the current tab.  Opening a link from Google makes it simply a new tab (i.e. not a child).  Can you confirm this, or is this specific to my setup?

**Comment by kopp** [comment]
@david-me : you're refering to issue #437 , correct?

**Comment by hukka** [comment]
@kopp Confirmed: Links from google seem to not work properly, unless I "interact" with the page first somehow. I don't know what exactly needs to be done, but at some point the links start to thread in same tree as the parent page.

I also noticed that there's no way to reopen this issue, so I suppose a new one must be made.

**Comment by david-me** [comment]
@kopp Yes, that's the issue I created. 
Even if I do interact with a page it still doesn't open a new tab as a child. This is with all extensions disabled except Conex, Tree Style Tabs, and Vim Vixen. If Conex is disabled I do get the same result as you (link not becoming child if from google but it does for github)
