### ISSUE TITLE
Search is contained for a single tab

### ISSUE THREAD

**Issue by hkupty** [ueokande/vim-vixen#285]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description

When searching, normaly I expect that vixen keeps the last searched expression so I can search it on other pages, but instead the search term is blank on a different page. 

The best approach would be to allow this behavior to be configured.

### Failure Information (for bugs)
On a different tab, the pressing `n` yields an error, causing me to rewrite the query.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open two tabs
2. On the first, `/some text` 
3. Go to the next,
4. `n` <-- yields an error of `Pattern not found: `

#### System configuration

- Operating system: Arch linux
- Firefox version: 57.0.2
- Vim-Vixen version: 0.7

#### Console logs

Any relevant log in developer tools:  No

**Comment by ueokande** [comment]
duplicated #218
