### ISSUE TITLE
I have to wait for the page to be fully loader before switching tab

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [ueokande/vim-vixen#287]
### I'm opening this issue because:

- [X ] I'll report a bug
- [ ] I'll propose a new feature

### Description
If I want to switch tab while the current tab is loading I can't, I have to wait for the page to have finished loading for J and K to be detected.
I didn't find this issue elsewhere so I decided to file it.
#### Steps to Reproduce
(Works on any page.)
1. click on a link, any link
2. while the page is loading, type J or K to change tab
3. see that you can't until the page is loader

#### System configuration

- Operating system:ubuntu 16.04
- Firefox version:57.01
- Vim-Vixen version:0.7

**Comment by ainola** [comment]
This is a limitation of webextensions in firefox: As the loading page is 'owned' by Firefox, the extension does not have permission to run at that time.

Perhaps a workaround would be for vim-vixen to open its own blank page before loading the new page. Not elegant, and I hope there's a better way.

**Comment by ueokande** [comment]
I recognize the issue, and I had tried to fix it.  In #104, `manifest.json` was modified as `"run_at": "document_end"` according to [MDN](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/content_scripts
), which loads a plugin on DOM loaded.  But actually, we have to wait for plugin enabled.

**Comment by ueokande** [comment]
I recognize the issue, and I had tried to fix it.  In #104, `manifest.json` was modified as `"run_at": "document_end"` according to [MDN](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/content_scripts
), which loads a plugin on DOM loaded.  But actually, we have to wait for plugin enabled.

**Comment by ueokande** [comment]
duplicated #156
