### ISSUE TITLE
 Console frame not hidden in fullscreen 

### ISSUE THREAD

**Issue by leo424y** [ueokande/vim-vixen#290]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description
https://accounts.firefox.com/oauth/signin

### Failure Information (for bugs)
iframe id = vimvixen-console-frame  didn't hide

﻿

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1 go to https://accounts.firefox.com/oauth/signin
2. you get it... iframe id = vimvixen-console-frame  didn't hide

#### System configuration

- Operating system: OSX 10.13.2 BETA
- Firefox version: 58.0b12 (64)
- Vim-Vixen version: 0.7
<img width="1440" alt="screen shot 2017-12-23 at 3 18 48 pm" src="https://user-images.githubusercontent.com/1384394/34317906-a950b102-e7f4-11e7-8167-90da571bfb84.png">

**Comment by ueokande** [comment]
maybe same issue with #189

**Comment by ueokande** [comment]
caused by Content Security Policy. duplicated #189
