### ISSUE TITLE
I translated part of this document into Chinese Simplified

### ISSUE THREAD

**Issue by ghost** [ueokande/vim-vixen#296]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description

Hi, author!

I like this add-on very much. I think it can imporve everyone's productivity, and I want to help Chinese programmer learn it to use. So I translated part of this document into Chinese.

The address is https://github.com/tdkihrr/vim-vixen-zh-cn.

Could you add it into your README.md？

**Comment by ueokande** [comment]
Thank you for your proposal, but it is hard to sustain it in the future for me.
