### ISSUE TITLE
Paste URL

### ISSUE THREAD

**Issue by ueokande** [ueokande/vim-vixen#3]
`p`/`P` command in Vimperator

**Comment by ueokande** [comment]
Getting data from a clipboard may not support in current browser.

**Comment by ueokande** [comment]
It may achieve by permission to access clipboard.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/permissions#Clipboard_access

**Comment by gliptak** [comment]
https://github.com/philc/vimium/pull/2601

**Comment by bovine3dom** [comment]
You might also want to look at https://github.com/cmcaine/tridactyl/blob/master/src/excmds.ts#L415 and https://github.com/cmcaine/tridactyl/blob/master/src/commandline_frame.ts#L141

**Comment by ueokande** [comment]
closed
