### ISSUE TITLE
List bookmarks in :open command

### ISSUE THREAD

**Issue by nickednamed** [ueokande/vim-vixen#302]
### I'm opening this issue because:

- [ ] I'll report a bug
- [X ] I'll propose a new feature

### Description
Most vim-like addons I've tried listed/searched my bookmarks upon pressing 'o' and entering some string. As it is, with Vim-Vixen, I must use Ctrl+L for this functionality.

Perhaps Vim-Vixen could just use FF's address bar to make use of this functionality?

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

#### System configuration

- Operating system:
- Firefox version:
- Vim-Vixen version:

#### Console logs

Any relevant log in developer tools:

**Comment by ueokande** [comment]
duplicated #145
