### ISSUE TITLE
Just stopped working (firefox-nightly)

### ISSUE THREAD

**Issue by xircon** [ueokande/vim-vixen#318]
On today's update, clicked OK, died.  Working up until this time.

**Comment by ueokande** [comment]
describe failure Information

**Comment by teranex** [comment]
I'm using Firefox-beta (58b16) on Ubuntu 17.10. vim-vixen 0.8 worked fine. Just upgraded to 0.10 and no single key (j, k, :, G, ...) wok anymore..
