### ISSUE TITLE
Unresponsive to any keyboard shortuts

### ISSUE THREAD

**Issue by dmusican** [ueokande/vim-vixen#319]
### I'm opening this issue because:

- [X ] I'll report a bug
- [ ] I'll propose a new feature

### Description

Vim-vixen seems to be entirely not working for me. Any website I go to; the keyboard shortcuts all do nothing.

#### Steps to Reproduce

Install Vim Vixen. Try to use it via various keyboard shortcuts. Nothing happens. :)

#### System configuration

- Operating system: Ubuntu 16.04
- Firefox version: 57.0.4
- Vim-Vixen version: 0.10

#### Console logs

Any relevant log in developer tools:

Whenever I try a Vim Vixen shortcut, I see this in the browser console, though I'm not sure if this is relevant:

TypeError: l.properties is undefined

**Comment by Nefari0uss** [comment]
Same for me as well.

System:

* OS: OSX (can check Windows/Arch later if needed)
* Firefox Nightly: v59
* Vim-VixenL 0.10

**Comment by ueokande** [comment]
I couldn't reproduce it, but TypeError seems vim-vixen's bug.
Did you try to restart Firefox?  If Vim Vixen still does not works, could you paste your configuration

**Comment by grissomwoo** [comment]
When updating Vim-Vixen to 0.10, keyboard shortcut cannot work on my Firefox v58.0. Then I enable smoothscroll in Vim-Vixen configuration page, these shortcuts work again.

**Comment by dmusican** [comment]
Wow @grissomwoo! Confirmed that enabling smoothscroll re-enables my keyboard shortcuts as well.

@ueokande: restarting Firefox doesn't help. Pardon my ignorance -- when you say "paste my configuration," could you be more specific what you're looking for?

**Comment by franciscoj** [comment]
Same here. Shortcuts not working at all until I enabled smoothscroll.

Firefox 59.0b2. Config pasted here: https://gist.github.com/franciscoj/10494ec2fc81a76d1aa688767daf3d65

**Comment by ueokande** [comment]
@grissomwoo Great solution, thank you very much
@dmusican Could you tell me which did you use, json or form settings, before resolved?  If json, paste it please.

**Comment by ueokande** [comment]
I could reproduce by following steps:
1. Install Vim Vixen 0.8
2. Switch form settings in extension settings
3. Install Vim Vixen 0.10
I will fix it and provide urgent release.  Thank you for your reports!!

**Comment by dmusican** [comment]
Thanks you, @ueokande!
