### ISSUE TITLE
Open tabs, windows without using the console

### ISSUE THREAD

**Issue by kartik-ynwa** [ueokande/vim-vixen#325]
### I'm opening this issue because:

- [X ] I'll propose a new feature

### Description

Is it okay if I code the option to open a new tab or a window without using the console so the users can take advantage of the Firefox omnibar if they want to? They need not be bound by default but it would be nice to have them.

**Comment by CallidusAsinus** [comment]
'f' followed by 'shift <link code>' perhaps?

**Comment by xaviershay** [comment]
Came here looking for this feature. Common use case for me is to search for something, open the top N results in background tabs, then switch to the tabs one by one.

**Comment by kartik-ynwa** [comment]
I'm sorry but what the previous commenter and you are talking about seems
to be different from what I suggested.

I was thinking about (for eg.) binding 't' to a new function which just
straight up opens an empty tab. Then you can use the omnibar which gives
you access to your bookmarks, history and search suggestions, something
that the command line (don't know the name for it) does not. Can do the
same with new windows via 'w'.

If the idea you have is different from this, can you clarify it a bit more?
If it is something that I find useful I may end up implementing it.

Thanks.

**Comment by CallidusAsinus** [comment]
I was imagining a feature that allowed you to follow on-screen links in a new tab. Presently you can seemingly only follow them in the same tab by hitting 'f' followed by the characters visually identifying the link.

**Comment by kartik-ynwa** [comment]
I believe you can do it with 'F' (Shift+'f') then the corresponding key
combination to open a link in a new tab. I don't know if there is a way to
follow links into a new tab that opens in the background though but it
should be easy to implement.

**Comment by mb720** [comment]
@astralspurs You can already do this. From [here](https://github.com/ueokande/vim-vixen/issues/403):

    "F": { "type": "follow.start", "newTab": true, "background": true },

**Comment by maturano** [comment]
> I was thinking about (for eg.) binding 't' to a new function which just straight up opens an empty tab

... Like `Ctrl+t`??? 🤔

**Comment by kartik-ynwa** [comment]
Fuck I am dumb
