### ISSUE TITLE
Is it possible to choose items from buffer/history

### ISSUE THREAD

**Issue by JosephLiuBin** [ueokande/vim-vixen#327]
### I'm opening this issue because:

- [ ] I'll report a bug
- [X ] I'll propose a new feature

### Description
Hi Ueokande,

When I click b or t or o and type in charaters, vim-vixen gives me buffer or history, but I could not choose item by clicking or pressing botton up and down. May I ask whether I miss anything or this function is still under construction?

Thanks and best Regards,
Joseph Liu 

#### System configuration

- Operating system: Win 10
- Firefox version:59
- Vim-Vixen version:0.11

#### Console logs

Any relevant log in developer tools:

**Comment by quinh** [comment]
You can use the **TAB** key in order to cycle through the list. If you've too many tabs oben, you can filter out by typing some characters from the name of your desired tab. Maybe that is what you want to use until this feature you requested gets implemented.

**Comment by JosephLiuBin** [comment]
Hi Quinh,

Thanks for your advice and it works for me now. ;)
