### ISSUE TITLE
Created an AUR package

### ISSUE THREAD

**Issue by mnussbaum** [ueokande/vim-vixen#328]
Hey I just wanted to let you know, I've created an [Arch Linux AUR package](https://aur.archlinux.org/packages/firefox-vim-vixen/) to install vim-vixen. I needed it for myself and thought it might be handy to others as well! I'll close this issue right away, just wanted to get word out.

Happy to make any changes you might to the package as well.

**Comment by Nefari0uss** [comment]
@mnussbaum Little confused as to why an AUR package is needed. Wouldn't you still have to open it via browser to install it?

**Comment by mnussbaum** [comment]
Nope, with the AUR package on Arch linux no need to open the browser. You can use an [AUR helper](https://wiki.archlinux.org/index.php/AUR_helpers) like `pacaur` to install the package and register it with your OS' package managment. You might do this on the CLI with:

```
pacaur -Syu firefox-vim-vixen
```

The extension's XPI file is downloaded from mozilla's extensions CDN and dropped into the directory that Firefox reads and writes extension packages to. The process is akin to [manually installing a Firefox extension](https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Extension_Packaging#Install_extension_files_directly). The browser picks up and handles the extension just as if you installed it via the browser UI.

As for my motivations, I prefer to use my OS' package manager to install Firefox extensions so that I can have a single interface for all software installed on my system. This makes it easier for me to configure my setup on a new computer as well as audit the software I'm currently running.

**Comment by Nefari0uss** [comment]
Gotcha. Thanks! I've never installed extensions via the AUR but I have a lot of experience using it otherwise.
