### ISSUE TITLE
Keybindings with Ctrl don't work anymore in firefox 59

### ISSUE THREAD

**Issue by bartlibert** [ueokande/vim-vixen#334]
### I'm opening this issue because:

- [X] I'll report a bug
- [ ] I'll propose a new feature

### Description
Any keybindings with "CTRL" stopped working in Firefox 59, while they worked OK in Firefox 58.
Probably something changed in Firefox, because something similar is present in vimium (https://github.com/philc/vimium/issues/2925)

#### Steps to Reproduce
  1. Use Firefox 59
  2. Try any shortcut that contains "Ctrl" on a page where vim-vixen is enabled, the results vary depending on the configuration:
    1. Keybinding with control is configured in vim-vixen and keybinding without control is configured in vim-vixen -> action without control is always executed. For example: with <C-o> bound to going back in history and "o" bound to open, pressing "o" and "<C-o>" always executes open
    2. Keybinding with control is not configured in vim-vixen, but is in Firefox. Keybinding without control in configured in vim-vixen. Result: vim-vixen action is always executed. For example: Pressing <C-l> to go to the location bar executes "scroll right" if "l" is bound to that action
   3. Keybinding with control is configured in vim-vixen and has an action in Firefox as well. Keybinding without control is not configured in vim-vixen. Result: firefox action is executed. For example: with <C-i> bound to going forward in history and "i" bound to nothing, pressing "<C-i>" show the page info dialog in Firefox.

#### System configuration

- Operating system: Debian buster
- Firefox version: 59.0b4
- Vim-Vixen version: 0.11

#### Console logs
No logs seen when pressing the keys.

**Comment by ueokande** [comment]
Firefox 59 is no longer supported.
If this issue is still valid, please open a new issues. Thank you for your proposal.
