### ISSUE TITLE
Can we add a shortcut for going back to the previous tab?

### ISSUE THREAD

**Issue by jingjingduan** [ueokande/vim-vixen#335]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description

I often want to go back to the previous tab after checking out another tab. Can you add a shortcut for that? Thanks!!!!

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

#### System configuration

- Operating system:
- Firefox version:
- Vim-Vixen version:

#### Console logs

Any relevant log in developer tools:

**Comment by ueokande** [comment]
press <kbd>Ctrl</kbd>+<kbd>6</kbd>

**Comment by jingjingduan** [comment]
Thanks for your quick response!

However, `Ctrl-6` doesn't seem to do anything. Let's describe my use case again to make it super clear. Let's say I'm working in one of the tabs and I'd like to check out gmail. After that, I'd like to go back to the tab where I was working in again. Is there a shortcut for that? Thanks again!

**Comment by ueokande** [comment]
@jingjingduan Did you configure the keymap `"<C-6>": { "type": "tabs.prevsel" }`?

**Comment by jingjingduan** [comment]
I just configured it and it's working great. Thanks again!
