### ISSUE TITLE
Filter labels like

### ISSUE THREAD

**Issue by cactustweeter** [ueokande/vim-vixen#336]
### I'm opening this issue because:

Navigation is not as obvious as it could be. 

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description

In Vimium after displaying link labels with keypress f, the next character I type shows just the labels matching that character I typed, and the remaining characters that need to be typed to select the associated link. Vim Vixen would be made better if it only displayed the remaining characters that are left to type to select a label instead of all the characters including ones that have already been typed because if you how to move away from Firefox and come back to it there's no indication of what is left to type to select a link. With Vimium it's evident what's left to be typed to select a link.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

#### System configuration

- Operating system:
- Firefox version:
- Vim-Vixen version:

#### Console logs

Any relevant log in developer tools:

**Comment by stonewareslord** [comment]
Vimperator/Pentadactyl had an option to modify a variable called `hintchars` (for example, the default was `set hintchars=0123456789`). If a user presses something not in `hintchars`, it gets filtered. This could be a good solution to your issue that VimVixen could implement. 

This would allow for a workflow similar to how Vimperator/Pentadactyl could be set up:

- `set hintchars=ASDFJKLHQWERZXCVUIOPNMBTY`
- When typing a lowercase letter or number, the hints are filtered
- When typing an uppercase letter, the hint is matched
- If there is only one hint on screen, it is automatically selected

**Comment by ueokande** [comment]
@stonewareslord Vim Vixen also supports `hintchars`.  I expect Cactustweeter said Vim Vixen should only display (or highlight) labels for the remaining characters.

1. displayed labels: |**A**| |**B**| |**C**| |**AA**| |**AB**|  |**AC**|
2. press <kbd>A</kbd>
3. displayed labels: |A**A**| |A**B**| |A**C**|

**Comment by stonewareslord** [comment]
It looks like VimVixen does support hintchars, but not filtering. You're right about what Cactustweeter is saying, I misunderstood. 

It would be nice, however, if VimVixen could be configured to work like Vimp/Pentadactyl in that it filters links *or* like Vimium and filter labels. For example when filtering links:

1. `hintchars=ABCD`
1. Webpage looks like: `Info|A| Download|B| About|C|`
1. Press `n`
1. Webpage looks like: `Info|A| Download|B| About`
1. Press `i` (matches `I` in info), or press `A` (is a hintchar, matches Info)
1. Webpage is redirected to `Info` URL

**Comment by ueokande** [comment]
duplicated #121
