### ISSUE TITLE
Support for containers

### ISSUE THREAD

**Issue by wladmis** [ueokande/vim-vixen#341]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description

Functionality to choose in which container new tab shall be opened. For hintable links keybinding could be sort of ';c'.

**Comment by ueokande** [comment]
duplicated #202

**Comment by wladmis** [comment]
It seems that you mark wrong issue as duplicated. Since I cannot reopen the issue I'll create a new one.

**Comment by ueokande** [comment]
sorry, I mistook
