### ISSUE TITLE
Issuing the next command, via "]]", doesn't work on Google

### ISSUE THREAD

**Issue by dmusican** [ueokande/vim-vixen#342]
### I'm opening this issue because:

- [X ] I'll report a bug
- [ ] I'll propose a new feature

### Description

Issuing the next command, via "]]", doesn't work on Google.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Go to google.com
2. Enter your favorite search word, and hit enter
3. Type ]]

At least in my case, I then end up at a "Brand Accounts" page. I can't even find that link in the search results page, though I assume it's buried there somewhere.

#### System configuration

- Operating system: Ubuntu Linux
- Firefox version: 58.0.2
- Vim-Vixen version: 0.11

#### Console logs

Any relevant log in developer tools:

**Comment by ueokande** [comment]
It seems work currently.  If this issue is still valid, please open a new issues. Thank you for your proposal.
