### ISSUE TITLE
Select tabs by URL or title does not work

### ISSUE THREAD

**Issue by wladmis** [ueokande/vim-vixen#352]
### I'm opening this issue because:

- [X] I'll report a bug
- [ ] I'll propose a new feature

#### Steps to Reproduce

1. press 'b' key
2. choose some title, then press enter
3. console outputs: a.title is undefined

#### System configuration

- Operating system: Linux
- Firefox version: 58.0.2
- Vim-Vixen version: 0.11

**Comment by myokoym** [comment]
Hi, I met almost the same probrem:

#### Steps to Reproduce

* press 'b' key
* choose some title, then press enter
* console outputs: **e**.title is undefined

#### System configuration

* Operating system: Debian GNU/Linux
* Firefox version: 60.0.1
* Vim-Vixen version: 0.14

**Comment by myokoym** [comment]
It was working fine until yesterday.

And, Ubuntu is OK (Firefox and Vixen versions are the same).

**Comment by myokoym** [comment]
The problem was solved after closed some tabs on my environment (details unknown).
