### ISSUE TITLE
iframe gets blocked and shows up as weird block on https://accounts.firefox.com

### ISSUE THREAD

**Issue by ijsnow** [ueokande/vim-vixen#369]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description

CSP blocks the iframe from loading on https://accounts.firefox.com(probably for good reason). This causes a weird block to show on the page. Also, the whole extension is pretty much broken on this page. I know that this is out of your control but maybe we could just not run the extension on sites like this.

#### Steps to Reproduce

1. Visit https://accounts.firefox.com and observe the weird block on the left side

#### System configuration

- Operating system: Mac
- Firefox version: Latest
- Vim-Vixen version: Latest

#### Console logs

Any relevant log in developer tools:

![screen shot 2018-04-05 at 11 42 42 am](https://user-images.githubusercontent.com/11557758/38385335-7f5fea48-38c6-11e8-8952-9a71479f9b94.png)

**Comment by ueokande** [comment]
Add-ons don't works in Mozilla's pages.  The might be caused by API limitation. That is discussed in #241.

**Comment by ueokande** [comment]
Although, I couldn't see Content Security Policy errors in https://accounts.firefox.com,  it is also discussed in #189.  Thank you.
