### ISSUE TITLE
Close all tabs right to current one

### ISSUE THREAD

**Issue by insilmaril** [ueokande/vim-vixen#371]
### I'm opening this issue because:

- [ ] I'll propose a new feature

### Description

Would be cool to have a function which closes all tabs right of current one. Of course bindable to a key :)

**Comment by LKlemens** [comment]
I agree, that feature would be very helpful :)j

**Comment by ueokande** [comment]
Here, what is the best keyso?  <kbd>Shift</kbd>+<kbd>D</kbd>?
