### ISSUE TITLE
ServiceNow web application does not display when Vim-Vixen is enabled 

### ISSUE THREAD

**Issue by infrascripting** [ueokande/vim-vixen#373]
### I'm opening this issue because:

- [X ] I'll report a bug

### Description

ServiceNow web application does not display when Vim-Vixen is enabled 

### Failure Information (for bugs)

`SecurityError: Permission denied to access property "document" on cross-origin object`

`SecurityError: Permission denied to access property "nodeType" on cross-origin object`

#### Steps to Reproduce

Go to any ServiceNow page with Vim-Vixen active

#### System configuration

- Operating system: MacOS
- Firefox version: FF61 (nightly)
- Vim-Vixen version: 0.12

#### Related

See: https://github.com/cmcaine/tridactyl/issues/279

EDIT: Blacklist the site does not work, as it is still refusing to load.

**Comment by ueokande** [comment]
duplicated #250?

**Comment by infrascripting** [comment]
Closing for duplicate #250
