### ISSUE TITLE
vim-vixen doesn't work on hub.docker.com

### ISSUE THREAD

**Issue by neilhwatson** [ueokande/vim-vixen#374]
### I'm opening this issue because:

- [x ] I'll report a bug
- [ ] I'll propose a new feature

### Description
vim-vixen doesn't work on hub.docker.com

### Failure Information (for bugs)
hjkl / and others don't work.

#### Steps to Reproduce
https://hub.docker.com

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

#### System configuration

- Operating system: Debian Jessie
- Firefox version: 59.02
- Vim-Vixen version: 0.12

#### Console logs

Any relevant log in developer tools:

**Comment by ueokande** [comment]
It seems work currently. If this issue is still valid, please open a new issues. Thank you for your report!
