### ISSUE TITLE
Ctrl+U default keybinding conflicts with "show source"

### ISSUE THREAD

**Issue by Lesik** [ueokande/vim-vixen#377]
### I'm opening this issue because:

- [ ] I'll report a bug
- [X] I'll propose a new feature

### Description

Firefox' default keybinding for "show source" is Ctrl+U. This conflicts with Vim Vixen. For web developers, this is really annoying. I propose to alter Vim Vixen's default keybindings to not conflict with Firefox default keybindings.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open any page.
2. Press Ctrl+U

Please note that I am aware of the option to configure keybindings manually. I am specifically proposing to alter the _default_ keybindings because imho addons shouldn't conflict with the base applications they are written for. This issue is open for discussion.

**Comment by omh5** [comment]
Well, Ctrl+U is a default Vim keybinding, that's why it's better to keep it as it is.
How about adding a new keybinding to show the page source, e.g. `vs` (for *view source*)?

**Comment by ueokande** [comment]
I suggest `gf` as it is a default keys in vimperator.

**Comment by omh5** [comment]
My suggestion is to stick to easy-to-remember keybindings, such as `vs` and `ss`, stand for *view* and *show source*, respectively. To me, the keybinding `gf` reads more like *go forward* than *view source* =)

**Comment by casperravenhorst** [comment]
I'd say keep Ctrl+U to scroll. It's not just default in vim, but in many terminal utilities, it's only natural. Also I never use view source, can't see what about it still has any use over the full Inspector. Also I have no horse in this race because on mac it's Cmd+U and thus doesn't shadow the default.

**Comment by omh5** [comment]
@ueokande this issue should be marked *closed*, as it was already solved in #279 and #368.

**Comment by Lesik** [comment]
@omh5 This is a discussion issue and thus not a duplicate of #279 nor #368.

**Comment by indeveler** [comment]
Why not to change shortcut to whatever you want?

![image](https://user-images.githubusercontent.com/1275668/42408357-9bdd3e14-81f5-11e8-8294-f1edf5350701.png)

**Comment by maturano** [comment]
Yep. The feature is implement and anyone have the option to configure the key stroke (I'm with `g+f`), so I think also as discussion should be closed.

**Comment by Lesik** [comment]
@indeveler A classic "I didn't even read the OP".

**Comment by indeveler** [comment]
@Lesik sorry, your right.

**Comment by ueokande** [comment]
Vim Vixen currently overrides many key mpas.  <kbd>Ctrl</kbd>+<kbd>U</kbd> is also general key mapping in Vim.
Firefox has many key maps, and it is difficult to avoid them.  I think what considering firefos's keymaps is impractical.
