### ISSUE TITLE
'n'/'N' keys should be ignored until '/' is pressed

### ISSUE THREAD

**Issue by AlexeySachkov** [ueokande/vim-vixen#396]
### I'm opening this issue because:

- I'll report a minor issue

### Description

Red overlay block appears if you typed `n`/`N` before `/`

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open any site (https://github.com)
2. Press `n` or `N`
3. You will see the following: ![image](https://user-images.githubusercontent.com/6417047/40121086-6c210d08-5929-11e8-9182-d97ecf4a11ab.png)

I think we should ignore `n`/`N` until search is started.

#### System configuration

- Operating system: Windows 10
- Firefox version: 60.0 
- Vim-Vixen version: 0.12

**Comment by ueokande** [comment]
Vim says when <kdb>n</kbd> pressed with no previous searchs:

```
E35: No previous regular expression
```

Vim Vixen should say such messages (e.g. "No previous search"...)

**Comment by AlexeySachkov** [comment]
@ueokande, looks like my vim saves last searched pattern somewhere. Even when I close the vim and reopen it again I cannot see message "No previous regular expression"

But i'm okay with something like "No previous search" instead of "Pattern not found: null". Looks more user-friendly

**Comment by ueokande** [comment]
current message expose the internal implementation.  I'll fix it in the next version.
