### ISSUE TITLE
Custom colors with a config file

### ISSUE THREAD

**Issue by ljoli** [ueokande/vim-vixen#400]
### I'm opening this issue because:

- [x] I'll propose a new feature

### Description

In vimperator, we can change the theme of FF 
I would like to custom with a specific file : 

https://github.com/vimpr/vimperator-colors

> This is a collection of colorschemes for Vimperator. I found most of them on the net. Maybe tweaked them to my liking.
> Put them in ~/.vimperator/colors and type :colorscheme theme-name in Vimperator.

#### System configuration

- Operating system: Ubuntu ( linux )
- Firefox version: 60.0.1
- Vim-Vixen version: 0.14

**Comment by ueokande** [comment]
discuss in #161
