### ISSUE TITLE
Invalid size and appearance of iframe with vim-vixen console on gcc.gnu.org

### ISSUE THREAD

**Issue by AlexeySachkov** [ueokande/vim-vixen#406]
### I'm opening this issue because:

-  I'll report a bug

### Description and failure information

I just observed that vim-vixen console (for `:t`, `:o` and other commands) appears really strange on gcc.gnu.org:

![image](https://user-images.githubusercontent.com/6417047/40846446-4ca87254-65c2-11e8-8745-b75a2109ff5d.png)

![image](https://user-images.githubusercontent.com/6417047/40846460-567f84ac-65c2-11e8-91e4-dc8c50e97541.png)

#### Steps to Reproduce

1. go to https://gcc.gnu.org
2. look at the console at bottom left side of the screen

#### System configuration

- Operating system: Win 10
- Firefox version: 60.0.1
- Vim-Vixen version: 0.14

**Comment by ueokande** [comment]
Thank you for your reporting.  This issue is caused by content security policy, see #189.
