### ISSUE TITLE
Use G/gg to go to bottom/top of page

### ISSUE THREAD

**Issue by rfblue2** [ueokande/vim-vixen#409]
### I'm opening this issue because:

- [ ] I'll report a bug
- [X] I'll propose a new feature

### Description
It would be really cool if we could type 'G' to jump to the bottom of the page and type 'gg' to go to the top of the page, as done in vim.

**Comment by stloma** [comment]
I believe that functionality has actually been available for a bit - are you running the latest version?

In the settings, they are:

```json
    "gg": { "type": "scroll.top" },
    "G": { "type": "scroll.bottom" },
```

**Comment by rfblue2** [comment]
I just checked and this appears to work!  Sorry for not being more thorough!
