### ISSUE TITLE
Smooth scroll is not smooth

### ISSUE THREAD

**Issue by ueokande** [ueokande/vim-vixen#425]
### I'm opening this issue because:

- [X] I'll report a bug
- [ ] I'll propose a new feature

### Description

Smooth scroll is supported by #307, but actually  it is not not smooth.  Vimium achieves really smooth scroll.
Vim Vixen should support such smoot scroll, too..

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Enable smooth scroll `:set smoothscroll`
2. Keep pressing <kbd>j</kdb>

#### System configuration

- Operating system:  Linux
- Firefox version:  Firefox 60.0
- Vim-Vixen version: 0.15

#### Console logs

Any relevant log in developer tools:

**Comment by jizef** [comment]
Maybe this is to reduce resource consumption XD

**Comment by hackel** [comment]
The current smooth scroll implementation behaves the same as using the arrow keys.  It scrolls one "line", then there is a short delay before scrolling resumes.  I would really like to eliminate this delay.

**Comment by ueokande** [comment]
memo: `scroll-behavior` is enable on FirefFox.
```css
html {
  scroll-behavior: smooth;
}
```

**Comment by adamijak** [comment]
Smooth scrolling still not enough smooth for me
