### ISSUE TITLE
Google Translate button click doesn't work

### ISSUE THREAD

**Issue by neochar** [ueokande/vim-vixen#426]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description
In google translate I'm often translate from one language to another and back, but I cannot switch language using vim-vixen.

### Failure Information (for bugs)
When I click `f` I see that buttons are clickable when I type neccessary button nothing happens.

#### System configuration

- Operating system: Linux Mint 18
- Firefox version: 61.0
- Vim-Vixen version: 0.15

**Comment by ueokande** [comment]
It seems work currently. If this issue is still valid, please open a new issues. Thank you for your report!
