### ISSUE TITLE
Appears to be corrupt

### ISSUE THREAD

**Issue by fargolo** [ueokande/vim-vixen#428]
### I'm opening this issue because:

- [X] I'll report a bug
- [ ] I'll propose a new feature

### Description
When adding Vixen to 62.0 (Ubuntu 16.04).  
#### Steps to Reproduce
Add Vixen in Firefox 62.0 (Ubuntu 16.04).  
#### System configuration

- Operating system: Ubuntu 16.04
- Firefox version: 62
- Vim-Vixen version: 0.15

#### Console logs

I don't know how to get the logs.

**Comment by ueokande** [comment]
@fargolo please open a new issue and describe details
