### ISSUE TITLE
Can't escape a tweet focus on twitter

### ISSUE THREAD

**Issue by J-Merle** [ueokande/vim-vixen#436]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description
When focusing a tweet on twitter, f doesn't recognize the X button to close the modal window.
I found no way to escape this view.

#### Steps to Reproduce

1. Go to https://twitter.com
2. Click on a tweet
3. Try to escape ...

#### System configuration

- Operating system: Antergos 18.7
- Firefox version: 61.0.1
- Vim-Vixen version: 0.15

**Comment by dsschnau** [comment]
I can reproduce this.

OS: Windows 10
FF version: 62.0.3
vim-vixen version: 0.19

**Comment by dsschnau** [comment]
Does vixen not target that 'X' because it's not a button, but rather a `<span>` with a click even handler?

**Comment by J-Merle** [comment]
I will close this issue because the way twitter is now displaying a tweet, you can easily use vim-vixen.
