### ISSUE TITLE
[Feature Request] Use search engines from Firefox preferences

### ISSUE THREAD

**Issue by sparkasaurusRex** [ueokande/vim-vixen#443]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description
Rather than having two locations for search engines (one in Firefox's preferences and one in Vim Vexen's config file), could you please look up the user's default search engine from Firefox's preferences? I would rather not specify my default search engine in two locations.

**Comment by ueokande** [comment]
duplicated #99
