### ISSUE TITLE
Fatal error when using the console: e.trimStart is not a function

### ISSUE THREAD

**Issue by chocolateboy** [ueokande/vim-vixen#449]
### I'm opening this issue to:

- [x] report a bug
- [ ] propose a new feature

### Description

In v0.16, pressing <kbd>t</kbd> or <kbd>:</kbd> results in the following error appearing in a red error bar at the bottom of the window:

> e.trimStart is not a function

This is due to the use of [`String#trimStart`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trimStart), which (as mentioned [here](https://github.com/ueokande/vim-vixen/blob/0.16/src/shared/urls.js#L2)) is only available in [Firefox 61](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trimStart#Browser_compatibility) and above.

#### System configuration

- Operating system: Linux (Arch)
- Firefox version: any version < Firefox 61 e.g. Waterfox 56.2.2 and Firefox ESR (60)
- Vim-Vixen version: 0.16

**Comment by ueokande** [comment]
@chocolateboy I've fixed it and release 0.17.  check it!

**Comment by chocolateboy** [comment]
Thanks, and greetings from 0.17! :tada:
