### ISSUE TITLE
:open shows a huge list of candidates

### ISSUE THREAD

**Issue by asavonic** [ueokande/vim-vixen#452]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description
After an upgrade from 0.16 to 0.17, :open and :tabopen commands show a lot of candidates (presumably all my history) instead of only a few (the most recent) candidates. It gets filtered out when I type, but initial list is slow and unusable.

#### System configuration

- Operating system: Linux
- Firefox version: 60.0.1
- Vim-Vixen version: 0.17 (regression from 0.16)

**Comment by ueokande** [comment]
@asavonic 
I cannot reproduce that, the history items are limited only 10 items.
Another possibility is you saw many bookmark items.

Bookmark items are no-limited.  All bookmark are shown on item completions.  Could you attach your screenshot?

**Comment by asavonic** [comment]
@ueokande ,
> Another possibility is you saw many bookmark items.

You're right, all items are bookmarks, not my history. Sorry for confusion.

> Bookmark items are no-limited.  All bookmark are shown on item completions

So this must be new in 0.17? How I can get the old behavior when bookmarks were limited?
I have many hundreds of bookmarks and this makes :open and :tabopen commands nearly unusable.

![ff-open](https://user-images.githubusercontent.com/3977995/43991340-8899bef6-9d73-11e8-9fbe-9447035b8743.png)

**Comment by johanberntsson** [comment]
Same problem here. In .016 the total amount of bookmarks and history was limited, but now :open covers the whole screen initially, which isn't good. At least consider to add a configuration option to limit the number of lines

**Comment by ueokande** [comment]
@asavonic that is an regression appeared on 0.17. thank you for your reporting.

**Comment by ueokande** [comment]
@asavonic The new version has been released.  Please check it!.

**Comment by asavonic** [comment]
Version 0.18 works great. Thanks a lot!
