### ISSUE TITLE
Can not open file: URL through :tabopen

### ISSUE THREAD

**Issue by casmarrav** [ueokande/vim-vixen#458]
### I'm opening this issue because:

- [X] I'll report a bug
- [ ] I'll propose a new feature

### Description
I have a file:// URL in my history. If I press `t`, type a word so that it comes up in the suggestions list, tab to it, and press enter, I get a red status box saying Illegal URL: and then the URL in question. I'd wish `t` would behave exactly like `Cmd+T` and then typing the URL.. is this another WebExtensions limitation?

### Failure Information (for bugs)
-

#### Steps to Reproduce
1. Press `t`
2. Type a file:// URL (existing .html file)

#### System configuration
- Operating system: MacOS
- Firefox version: 61.0.2
- Vim-Vixen version: 0.18

#### Console logs
Any relevant log in developer tools:
-

**Comment by ueokande** [comment]
duplicated #264, #106
