### ISSUE TITLE
Support Firefox for Android (Fennec)

### ISSUE THREAD

**Issue by robsmith11** [ueokande/vim-vixen#463]
About 80% of the features of Vim-Vixen work on Android (and is much faster than other vim-like addons on my tablet).

Most of the broken functionality is because Mozilla has not implemented all of the WebExtension APIs on Android yet.  Some features are impossible without the additional APIs, but I think a few workarounds could help it be more usable:

1. `command.show.open` is broken because `browser.history` is missing on Android.  If history support were disabled on Android, it should still work for opening URLs.

2. `browser.browserAction.setIcon` is undefined on Android, so the error message is always displayed at the bottom when a webpage with an icon is loaded.  This error could just be hidden on Android.

3. Text search and following links in a new tab fail silently without any error messages.  I'm not sure what's going on there, but maybe it's fixable.

**Comment by tombh** [comment]
Just wanted to chime in with more support. I've just started using Vim Vixen on Firefox mobile (Fennec) too and it makes a huge difference. The only problem I have is the `setIcon` error appearing at the bottom of a lot of pages. I'm happy to use `CTRL+t` instead of `o` and `CTRL+f` instead of `/`.

**Comment by robsmith11** [comment]
I've modified Vim Vixen to remove the unsupported API calls to prevent those error messages from appearing.

A proper fix (a conditional check on the API support before calling them) should be easy.  I don't know JavaScript, but if I have time later, I may try hacking together a pull request.

**Comment by robsmith11** [comment]
Finally got around to making a pull request for this issue:
https://github.com/ueokande/vim-vixen/pull/586

**Comment by robsmith11** [comment]
Closing this.. AFAIK the remaining missing features are caused by missing APIs that will hopefully be implemented by Mozilla someday.
