### ISSUE TITLE
Vixen not working on kotlin website

### ISSUE THREAD

**Issue by andre-cunha** [ueokande/vim-vixen#470]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description
Vixen scroll up/down (j/k) does not work on https://kotlinlang.org/docs/reference/

### Failure Information (for bugs)
https://kotlinlang.org/docs/reference/
#### Steps to Reproduce

Visit https://kotlinlang.org/docs/reference/
Press j or k -> no scroll action
#### System configuration

- Operating system: ubuntu
- Firefox version: 62
- Vim-Vixen version: 0.18

#### Console logs

Any relevant log in developer tools: N/A

**Comment by andre-cunha** [comment]
All other commands work just fine.

**Comment by pjotrek-b** [comment]
I can confirm this.
  * OS: Xubuntu 14.04
  * FF: v62
  * vim-vixen: 0.18

I'm not sure if I'm thread-hijacking, if I also report that vim-vixen does **not work** on other sites too.
For example: https://addons.mozilla.org/en-US/firefox/addon/hide-navigation-bar/

**Comment by ueokande** [comment]
Actually, only scroll does not work on kotlin website.  Please discuss in #235.

@pjotrek-b no addons works on AMO, see #241.
