### ISSUE TITLE
Cannot open in new tab

### ISSUE THREAD

**Issue by AkatsukiNin** [ueokande/vim-vixen#471]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description
Using the F shortcut doesn't open the link in new tab.

### Failure Information (for bugs)
"Error: Type error for parameter createProperties (Property "openerTabId" is unsupported by Firefox) for tabs.create."
#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Shift+F
2. Try to follow link
3. Loss??

#### System configuration

- Operating system: Win10 64-bit
- Firefox version: 55.0.3 (64-bit)
- Vim-Vixen version: 0.18

#### Console logs

Any relevant log in developer tools:

**Comment by ueokande** [comment]
That error occurs because `"openerTabId"` is supported on Firefox 57.
Firefox 55 is no longer supported. Please use latest (or supported ESR) version.
