### ISSUE TITLE
Question: Always display statusbar (console) with current URL?

### ISSUE THREAD

**Issue by pjotrek-b** [ueokande/vim-vixen#479]
### I'm opening this issue because:

- I have a question (sorry if this is not the right place)

### Description
Is it possible to display the console (statusbar) at all times?
Like in vimperator. So one can see the current URL (I've hid the navigation bar).

Thank you very much in advance.

**Comment by ueokande** [comment]
@pjotrek-b 
There are no ways to keep console shown in current specification.
In New WebExtension's API (not XUL), add-on can not render UI outside the page. So Vim Vixen needs inject console DOMs into the page. If the add-on keeps console shown, user cannot not see a part of the page under the console.

**Comment by ueokande** [comment]
that hiding issue is discussed in #203

**Comment by pjotrek-b** [comment]
@ueokande 
Oh... :disappointed:
But thanks for clearing that up!
