### ISSUE TITLE
Alternative hintchars setting

### ISSUE THREAD

**Issue by hejops** [ueokande/vim-vixen#480]
### I'm opening this issue because:

- [ ] I'll report a bug
- [ X ] I'll propose a new feature

### Description

The default setting for hintchars is simply a to z, which is somewhat irritating to type. hjklasdfgyuiopqwertnmzxcvb is a pretty commonly used setting. Could that be presented as an option (commented out if necessary)?

**Comment by casmarrav** [comment]
I've been wanting this feature as well (was in Vimperator), I might have some time today to PR that.

**Comment by AlexeySachkov** [comment]
Hi @hejops, @casmarrav 

Is [hintchars-property](https://github.com/ueokande/vim-vixen#hintchars-property) what you are looking for?

**Comment by ueokande** [comment]
use hintchars property
