### ISSUE TITLE
"Address was not understood" if the first search word ends with a ":"

### ISSUE THREAD

**Issue by bstaletic** [ueokande/vim-vixen#481]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Press `o` and do a search for `foo:`, you may also put anything after `:`.
2. Result: "The address was not understood" instead of doing a search, as happens when using the browser's address bar.

#### System configuration

- Operating system: Mint 19 amd64
- Firefox version: 61.0.1
- Vim-Vixen version: 0.18

#### Console logs

Any relevant log in developer tools:

**Comment by ueokande** [comment]
filed in #484
