### ISSUE TITLE
customize console colors

### ISSUE THREAD

**Issue by Salomanuel** [ueokande/vim-vixen#485]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description

It would be nice if the console (and all the other consoles, like `T`, `b`, `o` and such) could have customizable colors.   
Mostly because, with dark themes (and with Stylus or similar addons to change websites colors), suddenly having half the screen in a very bright white tends to blind the user.

#### Steps to Reproduce

1. theme everything with dark themes
2. be in a dark environment
3. change tab with `b`
4. BLOOD IS SPEWING FROM THE EYES

**Comment by ueokande** [comment]
discuss in #161
