### ISSUE TITLE
Question: How to bind Ctrl-Space

### ISSUE THREAD

**Issue by kcheang** [ueokande/vim-vixen#493]
### I'm opening this issue because:

- I have a question

### Description
I would like to bind Ctrl-Space to go to the last tab. I tried `"<C-Space>"` but it didn't work. How can I do this? Thanks!

**Comment by ueokande** [comment]
@kcheang 
Currently, to map <kbd>Ctrl</kbd>+<kbd>Space</kbd>, use `<C- >`.
But that is too confused for users.  I'll fix it and make it `<C-Space>` in the future.

**Comment by kcheang** [comment]
`<C- >` works. Thanks!
