### ISSUE TITLE
Doesn't respect default search engine

### ISSUE THREAD

**Issue by fowlie** [ueokande/vim-vixen#494]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description
When I use the open, winopen, or tabopen commands to do a search, it sends me to google.com - even though my default search engine with Firefox is duckduckgo.com.

#### System configuration

- Operating system: Windows 10
- Firefox version: 62.0.3 (64-bit)
- Vim-Vixen version: 0.18

**Comment by AlexeySachkov** [comment]
Hi @fowlie,

Looks like it is cannot be done by now due to API limitations. You can find some details in #99

**Comment by ueokande** [comment]
see  #99
