### ISSUE TITLE
Can't follow single char hints when there are many links

### ISSUE THREAD

**Issue by Linuus** [ueokande/vim-vixen#499]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description

When pressing `f` on a page where there are a lot of urls, I get both `A` and `AA` hints. The `A` hint is not possible to follow because it just waits for a second hint char.

**Comment by ueokande** [comment]
@Linuus press <kbd>Enter</kbd>
