### ISSUE TITLE
Way to unfocus url search bar?

### ISSUE THREAD

**Issue by jkieberking** [ueokande/vim-vixen#501]
### I'm opening this issue because:

Hi all, is there a way to unfocus the url search bar? One problem case is If I have a new tab open and I switch to it, my cursor automatically focuses on the search bar which stops me from being able to use any vim-vixen commands.

#### System configuration
 
- Operating system: mac HighSierrra 10.13.6
- Firefox version: 63.0.1
- Vim-Vixen version: .19

**Comment by ueokande** [comment]
WebExtensions cannot control URL search bar.  Please see also #148.

**Comment by wtberry** [comment]
If you still need, you can keep pressing tab key until it focus back on the webpage.
[Which is the keyboard shortcut to unfocus location bar?](https://support.mozilla.org/en-US/questions/1210451)

**Comment by LeonT-A** [comment]
> 
> 
> If you still need, you can keep pressing tab key until it focus back on the webpage.
> [Which is the keyboard shortcut to unfocus location bar?](https://support.mozilla.org/en-US/questions/1210451)

Ghetto, but with about a second of holding tab it works. Thanks a bunch!
