### ISSUE TITLE
Alternate Color Scheme for Dark Reader

### ISSUE THREAD

**Issue by jcbhghy** [ueokande/vim-vixen#514]
### I'm opening this issue because:

- [ ] I'll propose a new feature

### Description
While this addon works great without having dark webpages, it is nearly impossible to read the hints for navigation when the webpage is dark, such as when using the extension Dark Reader. If an option could be added (or exists that I haven't found) that could change the color of the hints to make them more readable, such as using white text (that would then be inverted to black with Dark Reader), it would make Vim Vixen even better in my book.

**Comment by ueokande** [comment]
Customizing styles is already required, please discuss in #161
