### ISSUE TITLE
Console is always visible on Lodash documentation

### ISSUE THREAD

**Issue by Lythenas** [ueokande/vim-vixen#519]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description

The VIm Vixen console is always visible on the documentation site of Lodash (https://lodash.com/docs/4.17.11). Also when the console is activated it has the same size and the top is cut off.

### Failure Information (for bugs)

Looking at the Inspector: The `.vimvixen-console-frame` styles don't show up, but the styles are present in the `<head>` tag.

#### System configuration

- Operating system: Linux
- Firefox version: 66.0a1 (64 Bit, Nightly)
- Vim-Vixen version: 0.19

#### Console logs

```
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“style-src”).
4.17.11:1:1
Error: Cannot set user agent for iframe with location different to this page content.js:150:17
fetch failed: https://www.google-analytics.com/analytics.js TypeError: NetworkError when attempting to fetch resource. sw.js:163:9
fetch failed: https://lodash.report-uri.io/r/default/csp/enforce TypeError: NetworkError when attempting to fetch resource.
sw.js:163:9
Loading failed for the <script> with source “https://www.google-analytics.com/analytics.js”. 4.17.11:1:1
fetch failed: https://cdn.carbonads.com/carbon.js?serve=CKYIEK37&placement=lodashcom TypeError: NetworkError when attempting to fetch resource. sw.js:163:9
Loading failed for the <script> with source “https://cdn.carbonads.com/carbon.js?serve=CKYIEK37&placement=lodashcom”. 4.17.11:1:1 
```

But not sure if any of that is relevant.

**Comment by ueokande** [comment]
Thank you for your reporting. This issue is caused by content security policy, see #189.
