### ISSUE TITLE
select item of completion

### ISSUE THREAD

**Issue by tsia** [ueokande/vim-vixen#522]
### I'm opening this issue because:

- [x] I'll report a bug
- [X] I'll propose a new feature

### Description

I'm not sure if it is a bug, it doesn't exist or of i'm just holding it wrong.

### Failure Information (for bugs)

When i use `:tabopen` for example and i have completion enabled i can't find a way to select an item form the completion list.

#### Steps to Reproduce

1. type `:tabopen<sp>something`
2. look for the line in the completion list
3. try to select it somehow

#### System configuration

- Operating system: Linux Debian 9.6
- Firefox version: 64.0.2
- Vim-Vixen version: 0.19

**Comment by AlexeySachkov** [comment]
Hi, @tsia 

You could use `tab` + `shift+tab` to select something from the completion list
