### ISSUE TITLE
Night mode [SUGGESTION]

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [ueokande/vim-vixen#525]
### I'm opening this issue because:
- [X] I'll propose a new feature

### Description
I am currently using my browser in the dark, with night mode addon enabled. The only thing flashing white on my screen and killing my eyes is vim-vixen when using "t", "o" ,":" etc commands. The "pop up" menu that appears is very white.

I think a more "greyish" color palette would be a good start but it's never a bad idea to add a dark mode to a plugin don't you think :) ?

(You did the most important firefox plugin IMO btw <3)

**Comment by AlexeySachkov** [comment]
Related to #161

**Comment by ueokande** [comment]
@thiswillbeyourgithub 
Thank you for your proposing, Configuring styles is already discussed, see #161
