### ISSUE TITLE
Unexpected error occurs when opening a page

### ISSUE THREAD

**Issue by pamolloy** [ueokande/vim-vixen#531]
### I'm opening this issue because:

- [X] I'll report a bug
- [ ] I'll propose a new feature

### Description
I am unable to open a page using Vim Vixen

### Failure Information (for bugs)

The Vim Vixen bar prints "An unexpected error occurred".

#### Steps to Reproduce
Open any page and type `o` as if to open a new page.

#### System configuration

- Operating system: Linux
- Firefox version: 67.0a1 (2019-02-01)
- Vim-Vixen version: 0.19

#### Console logs

Firefox debugging console prints:

```
TypeError: e.completions is undefined[Learn More]
```

I also see the following in the console, but it isn't clear if it is related:

```
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).
```

**Comment by pamolloy** [comment]
Just updated to 67.0a1 (2019-02-03) (64-bit) and I'm still experiencing the issue.

**Comment by GinGin3203** [comment]
I'm also on 67.0a1 and I'm experiencing the same issue. The same error pops up when using `:tabopen` or `:winopen`.

**Comment by ueokande** [comment]
@pamolloy 
I couldn't reproduce the problem with Vim Vixen 0.20 and Firefox 67.0a1(2019-02-15).
Could you tell me which site does the issue occues on?

**Comment by pamolloy** [comment]
Thanks for taking the time to try to reproduce it @ueokande.

Odd, I ran into it again on my work laptop after upgrading nightly this week. The website doesn't seem to matter. Is there any more debugging I could do on my end that would help?

**Comment by ueokande** [comment]
@pamolloy 

Could you tell me when you encounted the problem?  Are you new of Vim Vixen user? Or, have you used Vim Vixen with older Firefox (< 67)?  

To isolate causes, please try to use Vim Vixen with new profile.   In order to switch Firefox profile, launch it with command line `firefox -p` and select "Create Profile".
Thank you

**Comment by pamolloy** [comment]
I switched to Vim Vixen from vimperator when Firefox's plugin architecture changed. I've been using  Firefox Nightly for most if not that entire time.

I just upgraded to 67.0a1 (2019-02-16) and the issue went away!
