### ISSUE TITLE
can not configure X as tabs.reopen

### ISSUE THREAD

**Issue by jiahut** [ueokande/vim-vixen#540]
When Config with `X` as `tabs.reopen` 

it reports `Error: Unknown property name with "adjacent tab" `

**Comment by ueokande** [comment]
@jiahut 
Please remove `"adjacenttab"` settings in the `"properties"` from your configuration.

**Comment by ueokande** [comment]
DId you resolve it?
If this issue is still valid, please open a new issues. Thank you for your proposal.
