### ISSUE TITLE
VimVixen breaks Storybook

### ISSUE THREAD

**Issue by Vinnl** [ueokande/vim-vixen#549]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description

[Storybook](https://storybook.js.org/) is a tool used by front-end developers to try out their components in isolation. They recently released a new version with a new web interface, but for some reason, that breaks when used in combination with VimVixen: you end up at a blank page, and errors about an iframe's `contentDocument` being `null` in the console.

### Failure Information (for bugs)

See logs at the bottom of this bug report.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Visit [this demo instance](https://storybooks-official.netlify.com/) of Storybook with VimVixen installed.
2. Notice how you end up at a blank page and with errors in the console.
3. Visit that page again in a browser without VimVixen installed. You should see Storybook as it's supposed to be.

#### System configuration

- Operating system: Ubuntu 18.04.2
- Firefox version: 65
- Vim-Vixen version: 0.20

#### Console logs

Any relevant log in developer tools:

> TypeError: iframe.contentDocument is null

**Comment by smlx** [comment]
This seems fixed in 0.22?

**Comment by ueokande** [comment]
it works

**Comment by Vinnl** [comment]
It required upgrading to a new version of Storybook (we're at v5.0.11 compared to 5.0.1 when I created this issue), but I can confirm that it works then. Thanks!
