### ISSUE TITLE
Vim Vixen breaks hexed.it

### ISSUE THREAD

**Issue by codehearts** [ueokande/vim-vixen#558]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description
When I visit hexed.it, the upper toolbar is missing. Disabling Vim Vixen resolves the issue

### Failure Information (for bugs)
The page usually has a black toolbar at the top for opening files, but it's missing and there's some strange padding at the bottom of the page. It looks like an empty iframe is being displayed as well

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Visit hexed.it
2. Observe there is no black toolbar at the top of the page

#### System configuration

- Operating system: Windows 7
- Firefox version: 66.0.2 (64bit)
- Vim-Vixen version: 0.21

#### Console logs

Any relevant log in developer tools:

    Content Security Policy: The page’s settings blocked the loading of a resource at inline (“style-src”).

**Comment by ueokande** [comment]
caused by CSP, duplicated #189
