### ISSUE TITLE
Please remove or change D shorcut

### ISSUE THREAD

**Issue by anotherlog** [ueokande/vim-vixen#563]
Hi,

Would it be possible to change or remove the 'D' shortcut?
It's an easy mistake to type it and you end up closing 100 tabs without being able to reopen them... It happened a few times and it's quite frustrating. And I don't think I am the only one with the issue. 
Thanks in advance !

**Comment by gogron** [comment]
go to Add-ons -> vixen preferences and you can remap all keys. "d": { "type": "tabs.close" }, change or delete the key in braces

**Comment by anotherlog** [comment]
Wow, never seen that we could edit shorcuts... (A new world opens)
Thanks a lot !
