### ISSUE TITLE
Smooth scrolling option

### ISSUE THREAD

**Issue by mathstuf** [ueokande/vim-vixen#57]
### I'm opening this issue because:

- [x] I'll propose a new feature

### Description

Scrolling by pages is abrupt. An option to smoothly scroll would be nice.

#### Steps to Reproduce

1. Scroll using a keybind
2. Movement is instantaneous.

#### System configuration

- Operating system: Linux
- Firefox version: 57
- Vim-Vixen version: 0.1

**Comment by fane89** [comment]
Came here to add issue. Found this! +1

**Comment by helpermn** [comment]
Please implement this.

**Comment by madsystem** [comment]
+1. 

PS: Thanks for the plugin!

**Comment by MarekBielik** [comment]
+1

**Comment by Lesik** [comment]
Maybe it's just me, but I find the #307 implementation impossible to use. The scrolling is smooth if you press the key once, but if you press it multiple times, or worse, hold it, it stutters horribly. Is everybody else not experiencing this or just not bothered by this?
