### ISSUE TITLE
Kindle Cloud Reader doesn't load books since 0.22

### ISSUE THREAD

**Issue by astier** [ueokande/vim-vixen#577]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description

Since Release 0.22 the [kindle-cloud-reader](https://read.amazon.com/) doesn't load books anymore if vim-vixen is enabled in firefox. It simply keeps loading forever and never finishes. Blacklisting the website doesn't help. The addon must be disabled or removed completly.

#### Steps to Reproduce

1. Install and enable vim-vixen in firefox
2. Try to open a book in the kindle-cloud-reader
3. See that the book loads forever but never finishes
4. Disable or remove vim-vixen from firefox
5. Try to open a book in the kindle-cloud-reader
6. See that it now loads

#### System configuration

- Operating system: Arch Linux
- Firefox version: 66.0.3
- Vim-Vixen version: 0.22

#### Console logs

How do I get this?

**Comment by astier** [comment]
If I install 0.21 it works again.

**Comment by denharad** [comment]
I'm having the same problem with Solarwinds Nable Dashboard, It never gets to the two factor sign in & just shows the loading animation. Blacklisting does not help, but prior versions of Vim Vixen have no issue. This occurs on both Windows & Linux. Since this is a privately hosted site I can't reproduce it here, are there any troubleshooting steps I can take to help fix this?

**Comment by astier** [comment]
If we take a look at the [introduced changes by 0.22](https://github.com/ueokande/vim-vixen/releases/tag/0.22) it may be because of #571

**Comment by ueokande** [comment]
I dont have no books on kintone cloud.
Does anyone know some sites we can reproduce the issue on?

**Comment by astier** [comment]
Suddenly it works for me. @ueokande whats about you? Can you try it again and report if you still have this issue?

**Comment by denharad** [comment]
Nah, the problem still exists for my use case. I'm trying to find a way to prevent the add-on from running in a single tab as this is the only site that breaks, but so far I haven't had much luck.
