### ISSUE TITLE
Addon enabled, but not functioning since Firefox 66.0.4 fix on Windows

### ISSUE THREAD

**Issue by cyberjunkie2k** [ueokande/vim-vixen#581]
### I'm opening this issue because:

- [x] I'll report a bug

### Description
Ever since the Firefox 66.0.4 fix has been released, Vim Vixen seems to have stopped working. The add-on is enabled but none of the shortcuts seem to work. I will attempt it at home as well.

Customization menu has disappeared too.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Use the default scroll up/down keys, or any shortcut for that matter
2. Nothing works

#### System configuration

- Operating system: Windows 10
- Firefox version: Firefox 66.0.4 (64-bit)
- Vim-Vixen version: 0.21

**Comment by DamonDBT** [comment]
Have you erver solved this problem?
Now  i  also append some problem like yours on win 10 ,but only some upper case function like J K G  failed...
