### ISSUE TITLE
Vim Vixen could not be verified for use in FireFox Developer Edition

### ISSUE THREAD

**Issue by doMynation** [ueokande/vim-vixen#582]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description

Hi, I love this extension so I'd like to first take this opportunity to thank the maintainer(s).

This morning FireFox Developer Edition apparently no longer accepts this extension saying that it isn't verified.

https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct

### Failure Information (for bugs)

![image](https://user-images.githubusercontent.com/1403529/57230560-9d13ea00-6fe6-11e9-988a-bce7a85959bf.png)

![image](https://user-images.githubusercontent.com/1403529/57230688-ef550b00-6fe6-11e9-9cf0-96e2407bebf0.png)

#### Steps to Reproduce

Try installing or updating the addon.

#### System configuration

- Operating system: Windows 10
- Firefox version: FireFox Developer Edition 67
- Vim-Vixen version: 0.22

**Comment by ueokande** [comment]
@doMynation 
Because of expired certificate, see the following article:
https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

 Please update your firefox to latest version (67.0b17).
