### ISSUE TITLE
Smooth update procedure

### ISSUE THREAD

**Issue by AlexeySachkov** [ueokande/vim-vixen#598]
### I'm opening this issue because:

- I'll report a bug

### Description

Vim-vixen on my machine has been recently silently updated to 0.23 and now it is not working completely.

I've figured out what is wrong: my config file is not compatible anymore with the actual version.
I've tried to find default config in the repo to update mine, but failed to do so. I just re-installed vim-vixen to get new default config and merge it with mine.

I think it would be nice to have a link in README to the latest actual default config to be able to adjust your own settings to it.
Also I think that vim-vixen should either accept older config formats or automatically or semi-automatically update user's config to the newest format.
Something like notification message that config file cannot be read would be good too.

### Failure Information (for bugs)

Vim-vixen ignores any keys I type

#### Steps to Reproduce

1. Install the latest vim-vixen
2. Remove `"blacklist": []` section from config
3. Vim-vixen doesn't work anymore

#### System configuration

- Operating system: Win10
- Firefox version: 67.0
- Vim-Vixen version: 0.23

#### Console logs

Any relevant log in developer tools:

```
TypeError: "current is undefined"
    initSettings moz-extension://ab6df2ce-7e0f-45f0-a560-0ae639abacfe/build/content.js:4172
```

```javascript
let SettingController = class SettingController {
    constructor(addonEnabledUseCase, settingUseCase) {
        this.addonEnabledUseCase = addonEnabledUseCase;
        this.settingUseCase = settingUseCase;
    }
    async initSettings() {
        try {
            let current = await this.settingUseCase.reload();
            let disabled = blacklists.includes(current.blacklist, window.location.href); // current is undefined here
```

**Comment by BenElgar** [comment]
I had a similar issue: after upgrade nothing was working and it turned out my settings had been emptied, as shown below. 
<img width="646" alt="image" src="https://user-images.githubusercontent.com/3443024/58628181-f9f67d80-82d0-11e9-8519-d74999488511.png">
 
Fixed by adding `{}` to the empty JSON input and then switching back to the form settings.

**Comment by ueokande** [comment]
Umm... that is a bug occurs on 0.23.  I expect that users does not need to do nothing on upgrading.

Default config is definied [here](https://github.com/ueokande/vim-vixen/blob/master/src/shared/SettingData.ts#L330).  As @BenElgar seid, you can also use default config with empty JSON `{}`.

**Comment by ThomasAH** [comment]
I just came here to say +1
This happened on three different machines: Two with Linux (Debian with Firefox ESR) and one with Windows (with Firefox release)

**Comment by ThomasAH** [comment]
After removing `"adjacenttab": true` (and the trailing comma on the previous line) from the properties section it works again for me.
