### ISSUE TITLE
Preferences broken

### ISSUE THREAD

**Issue by suuuehgi** [ueokande/vim-vixen#599]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description
Preferences broken

#### Steps to Reproduce
Install the plugin. Configure window is empty, by clicking on _form_, the following appears:

![vim](https://user-images.githubusercontent.com/7861774/58953188-00d03500-8796-11e9-9b95-82e4a2f61c0e.jpg)

#### System configuration

- Operating system: Arch Linux 5.0.11
- Firefox version: 67.0.1 (64-bit)
- Vim-Vixen version: 0.23

Possibly related to  #556

**Comment by ueokande** [comment]
Please set `{}` to textarea. 
(refer #598)
