### ISSUE TITLE
Option to open tabs from follow in the background

### ISSUE THREAD

**Issue by mathstuf** [ueokande/vim-vixen#60]
### I'm opening this issue because:

- [x] I'll propose a new feature

### Description

It'd be nice to be able to have new tabs opened from follow hints to be done in the background.

**Comment by mathstuf** [comment]
Ugh, I can't find any documentation on WebExtensions to see what kind of fields on the message to open a new tab are available. Where does this information live?

**Comment by ueokande** [comment]
@mathstuf Thank you for proposing a new one.

> It'd be nice to be able to have new tabs opened from follow hints to be done in the background.

Do you mean that it opens a new tab by following link but the tab does not get a focus?  You could find that information about tab creating from following link: 
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create

Maybe it works with `active` option.

**Comment by mathstuf** [comment]
Right. The code opens tabs by using sendMessage which has sparse documentation it seems.

**Comment by ueokande** [comment]
maybe that can be achieve with changes in #62 (key maps is provisional and PR is under WIP)

**Comment by mathstuf** [comment]
Ah! I hadn't realized that the messages were being parsed in the code in the repository as well. That seems sensible to me.
