### ISSUE TITLE
Map Ctrl+C to "Esc"

### ISSUE THREAD

**Issue by peteygao** [ueokande/vim-vixen#603]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description
Map Ctrl-C to the same behaviour as "Esc" (or cancel).

It's muscle memory for me to use Ctrl+C in VIM to escape from, e.g. insert mode or visual mode, or to quit from the console (after typing `:`). With Vim Vixen, I'm having a hard time getting rid of the habit of using Ctrl+C when I inadvertently bring up the console (either pressing `b`, `t` or some other key). Having to reach for Esc is a minor hassle :wink:.

**Comment by sigboe** [comment]
+ one for this, its in default in vim. 

Sidenote: Using Caps Lock as Control makes this much more ergonomic :smile:
