### ISSUE TITLE
Add :help to open commands list

### ISSUE THREAD

**Issue by cirelli94** [ueokande/vim-vixen#605]
### I'm opening this issue because:

- [ ] I'll report a bug
- [ X] I'll propose a new feature

### Description
It would be helpful to have a fast way to check commands, I think and :h or :help command should be fine.

#### Steps to Reproduce
Open Console command
Type `:h` or `:help`
Please provide detailed steps for reproducing the issue.

I'd like to do this by myself, as a contributor.

**Comment by AlexeySachkov** [comment]
Looks like duplicate of #239

**Comment by ueokande** [comment]
see #239
