### ISSUE TITLE
How to use the `open` menu?

### ISSUE THREAD

**Issue by JacksonKearl** [ueokande/vim-vixen#611]
### I'm opening this issue because:

- [ ] I'll report a bug
- [ ] I'll propose a new feature
- [x] I'll propose new documentation

### Description
I have no clue how to actually use the entries I see in the open menu. In particular, bookmarks. How do I select bookmarks I see? Or history items? I can type the full name, then as soon as I hit enter I just get a google search.

**Comment by AlexeySachkov** [comment]
Hi, @JacksonKearl,

Here is mine workflow:
Push `t` to open vim-vixen console, then:
* if I want to search something I just write my query and press `Enter`
* If I've already visited the page I'm looking for, it appears in the console and I'm using `Tab` to select it and then `Enter` to open it
* If I want to search something concrete, I use pre-configured search engines. For example I can write "wikipedia something" to search "something" directly on wikipedia site

**Comment by JacksonKearl** [comment]
Ah, `Tab` did it. Still, documenting this *somewhere* would be nice... maybe I just missed it. Thanks!
