### ISSUE TITLE
Disable Showing History/Bookmark in 'open' command

### ISSUE THREAD

**Issue by DelonShen** [ueokande/vim-vixen#615]
### I'm opening this issue because:

- [x] I'll propose a new feature

### Description
Allow the user to disable displaying history/bookmarks in the 'open' menu

#### System configuration

- Operating system: Linux
- Firefox version: 67.0.4
- Vim-Vixen version: 0.23

**Comment by AlexeySachkov** [comment]
Hi @DelonShen, please take a look at [properties section](https://github.com/ueokande/vim-vixen#properties) in the README
