### ISSUE TITLE
Reduce font size of the yellow follow link boxes

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [ueokande/vim-vixen#619]
### I'm opening this issue because:

- [ X ] I'll report a bug
- [ X ] I'll propose a new feature

### Description
For a while I have been bothered by the size of the font in the yellow boxes that allow to follow links when pressing 'f'. It is most often a problem when browsing wikipedia and trying to switch language : they overlap, making it hard to distinguish quickly and they occlude the link underneath, allowing for errors in selecting the langage.

Here's a screenshot : 
![screen](https://user-images.githubusercontent.com/26625900/61577319-66257e80-aad5-11e9-8e7e-dbaf3cea46b2.png) when browsing in small font
![Screenshot from 2019-07-20 12-03-52](https://user-images.githubusercontent.com/26625900/61577347-c1f00780-aad5-11e9-960e-d3ce3a393b48.png) when font size is correct for my screen

The problem is not obvious with links boxes beginning with A but when having to distinguish between R, Q O it gets annoying 

I think that I good fix would be to reduce the font or to allow to change the font size in about:config.

### Please provide detailed steps for reproducing the issue.

press f on a long wikipedia page and look on the left at the language selection list. Notice that they overlap and are hard to read

**Comment by AlexeySachkov** [comment]
Related to #161

**Comment by ueokande** [comment]
see  #161
