### ISSUE TITLE
Needs visual Overhaul

### ISSUE THREAD

**Issue by NicTanghe** [ueokande/vim-vixen#630]
### I'm opening this issue because:

- [X] I'll propose a new feature

### Description

The letters when you pres F are realy ugly after using Vimium it hurts my brain.

Please make it prettier with rounded corners and a drop shadow

**Comment by NicTanghe** [comment]
i could help if you point me to where i can find that part of the code.

**Comment by ueokande** [comment]
@NicTanghe 
Thank you for your reporting.

What is your problem, and what behavior make you so better for you ?
Please describe to reproduce what you expected.

**Comment by NicTanghe** [comment]
there is nothing not working and functionally evrything is ok.

i'm reporting the letters when pressing f are ugly and could use a makeover.

**Comment by casperravenhorst** [comment]
@NicTanghe https://github.com/ueokande/vim-vixen/blob/master/src/content/site-style.ts#L16

**Comment by ueokande** [comment]
Thank you for your reports.

Customizing a style in Vim Vixen is discussed in #161.
