### ISSUE TITLE
Blacklist does not work for a specific file type (Jupyter notebook, "*.ipynb").

### ISSUE THREAD

**Issue by anlif** [ueokande/vim-vixen#636]
### I'm opening this issue because:

- [ x] I'll report a bug
- [ ] I'll propose a new feature

### Description
Blacklist does not work for a specific file type (Jupyter notebook, "*.ipynb").

#### Steps to Reproduce

1. Add the Blacklist pattern "*.ipynb"
2. Open a Jupyter Notebook with extension ".ipynb"
3. Observe that the plugin is not disabled

#### System configuration

- Operating system: Ubuntu 18.04
- Firefox version: 68.0.2 (64-bit)
- Vim-Vixen version: 0.23

**Comment by ueokande** [comment]
@anlif 
Sorry to late replying.

Blacklist treats "*.ipynb" as a domain name matching. So it matches with `foo.ipynb` and `bar.ipynb/index.html`, but not `foo.example.com/v1/fizzbuzz.ipynb`.

Please try wildcards with path separator: `*/*.ipynb`
Please try wildcards with path separator:  `*/*.ipynb`

**Comment by anlif** [comment]
This works! Thank you.
