### ISSUE TITLE
IFRAME is injected on blacklisted sites

### ISSUE THREAD

**Issue by richardb64** [ueokande/vim-vixen#645]
### I'm opening this issue because:

- [X] I'll report a bug
- [ ] I'll propose a new feature

### Description
When Vim-Vixen is configured to "blacklist" a site or partial URL, it seems still to inject its console IFRAME.  The existence of this frame is sufficient to break some web sites.

### Desired Behaviour
When Vim-Vixen is configured to be disabled on a particular site or page, it should not modify the DOM at all.

#### Steps to Reproduce
1. Identify a site which breaks when Vim-Vixen is enabled, due to an IFRAME-related issue (eg. #250, #373).
2. Add the site to the V-V blacklist.
3. Visit the site and observe that it is still broken.
4. Using the Firefox debugger, observe that the V-V IFRAME is still present in the DOM.

#### System configuration
- Firefox version: 69.0
- Vim-Vixen version: 0.24

#### Console logs
The precise error will depend on what the web site is trying to do, but typically it will be a variation on `SecurityError: Permission denied to access property "document" on cross-origin object`

**Comment by suuuehgi** [comment]
Still present on v0.26. I need to disable the plugin in order to be able to read the mails.

**Comment by mwuttke97** [comment]
Hi. Until this issue is resolved, I've found a workaround/hack for this. I created a simple Greasemonkey user script, that just removes the `iframe` from the site.

<https://gist.github.com/mwuttke97/59423820c86ac3f76635aeb31f8c17b6>

**Comment by richardb64** [comment]
Bumping this issue, as it's still present in the latest version of VimVixen.  The userscript posted by @mwuttke97 does the trick, but it would be better not to have to use it!
