### ISSUE TITLE
Opening a new tab with 'F' doesn't honour "When you open a link in a new tab, switch to it immediately" Firefox setting

### ISSUE THREAD

**Issue by tomboland-vocovo** [ueokande/vim-vixen#646]
### I'm opening this issue because:

- [x] I'll report a bug/feature request

### Description
I love and rely on Vim-Vixen, so thank you! 

When opening a new tab with 'F', I think vim-vixen should honour the firefox setting: "When you open a link in a new tab, switch to it immediately"

At the moment, I have this option disabled, but vim-vixen will switch to new tabs immediately.  It's a bit frustrating, because until that new tab has loaded, I can't gT back to the tab I was on. I quite often read through an article, and want to open tabs to look at later on, but without interrupting the current article

#### Steps to Reproduce
Ensure The firefox preference "When you open a link in a new tab, switch to it immediately" is unchecked
Hit 'F' and follow a link to open a new tab

#### System configuration

- Manjaro Linux
- Firefox 69
- Vim-Vixen 0.24

**Comment by AlexeySachkov** [comment]
@tomboland-vocovo, I don't know if it is possible to extract browser settings in plugin, but this particular behavior can be achieved by configuring vim-vixen, see [navigation](https://github.com/ueokande/vim-vixen#navigation) section in the README

**Comment by tomboland-vocovo** [comment]
Hi @AlexeySachkov, that's absolutely perfect for me, thank you very much!  I'll close this issue now, thanks again!
