### ISSUE TITLE
Support keyword search in :open and :tabopen?

### ISSUE THREAD

**Issue by chen-chao** [ueokande/vim-vixen#656]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description

Firefox's "add keyword for this search" is quite useful for simple customized searching queries. For example, if I add "https://github.com/search?q=%s&type=" bookmark with keyword "github", I can type "github vim vixen" in the address bar to search for vim vixen in github. It is similar or rather an enhancement to #145. 

Thanks.

**Comment by AlexeySachkov** [comment]
@chen-chao, I think this functionality is already supported, please take a look at documentation for [search engines](https://ueokande.github.io/vim-vixen/search_engines.html)

**Comment by ueokande** [comment]
@chen-chao 
You can register a search engine by the keyword:
```json
  "search": {
    "default": "google",
    "engines": {
      "google": "https://google.com/search?q={}",
      "github": "https://github.com/search?q={}&type="
    }
```

Then, press <kbd>:</kbd> and type `open github foobar`

**Comment by chen-chao** [comment]
Thanks for your replies! 

I know adding new search engines could do it. But the difference is that keyword search is in fact a bookmark. Now `:open` treats these "searching bookmarks" as normal bookmarks, which will end up in a google search(because they are not normal urls). For example "github repo searching" is bookmarked as "https://github.com/search?q=%s&type=".

**Comment by chen-chao** [comment]
I've found the firefox api limited the access to bookmark's keyword and tag field. So it's not possible to add the keyword bookmarks to vim-vixen's search engines now.
