### ISSUE TITLE
Toggle on Vixen on blacklisted site

### ISSUE THREAD

**Issue by unaimillan** [ueokande/vim-vixen#661]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description
It's impossible to toggle on Vim-Vixen with "Shift-Esc" when you are on a blacklisted website.

#### Steps to Reproduce

1. Blacklist any website through the JSON settings ( all/"*" in particular)
2. Try to toggle on Vixen with "Shift+Esc"
3. You get it...

#### System configuration

- Operating system: Ubuntu 19.04
- Firefox version: Mozilla Firefox 69.0.2
- Vim-Vixen version: 0.25

**Comment by ueokande** [comment]
@unaimillan Thank you for your reporting, it have been fixed 0.26.
