### ISSUE TITLE
Make it possible to disable extension for a particular URL pattern

### ISSUE THREAD

**Issue by wrongway4you** [ueokande/vim-vixen#67]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description

It is sometimes needed to disable the extension on a particular set of web-applications. This option should be present in the configuration of the extension.

The user should be able to enter a list of regular expressions, and, the extension would be disabled on the web-pages, URL of which matches at least one of the specified patterns.

**Comment by lukeallister** [comment]
I agree, this would be a great enhancement. I currently have to manually disable it when I want to navigate certain sites.

**Comment by ueokande** [comment]
duplicated: #11
