### ISSUE TITLE
Do we have control over completion suggestions?

### ISSUE THREAD

**Issue by jflorian** [ueokande/vim-vixen#68]
### I'm opening this issue because:

- [ ] I'll report a bug
- [X] I'll propose a new feature (or need help)

### Description

In various VIM-ish extensions I've previously used, some had the ability to let me choose and/or prioritize where completion suggestions (for `:open`, `:tabopen`) come from (e.g., bookmarks, history, keywords, etc.).  Does vim-vixen provide this?  If I'm not mistaken, it's using *only* history ATM.  Well, that and suggesting search engines.

I curate my bookmarks and given them keywords to greatly aid my suggestions; or so it was with say, VimFx.

#### System configuration

- Operating system: Fedora 26 x86_64
- Firefox version: 57.0b6 (64-bit)
- Vim-Vixen version: 0.1

**Comment by geeanlooca** [comment]
@ueokande Has this feature been implemented? I suddenly get bookmarks suggestions using `:open` command. This is problematic as the first few letters I type after calling the command with the `o` key are extremely slow as a relatively big list of bookmarks has to be parsed to be filtered
