### ISSUE TITLE
Vim Vixen blacklist doesn't turn off the plugin on a blacklisted site

### ISSUE THREAD

**Issue by FPFanatic** [ueokande/vim-vixen#686]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description
Vim Vixen's blacklist feature doesn't seem to work properly

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Add ```"youtube.com/*"``` to blacklist to use YouTube's shortcuts so the blacklist block looks like
```
  "blacklist": [
    "youtube.com/*"
  ]
```
2. Go to YouTube
3. Click on a video
4. Press ```f``` to go into full-screen mode
5. YouTube goes into full-screen, but Vim Vixen also puts up the link hints over the video

#### System configuration

- Operating system: Fedora 31
- Firefox version: 70.0.1
- Vim-Vixen version: 0.25

#### Other
If requested, I will gladly provide a gist of the entire config JSON form

**Comment by ueokande** [comment]
@FPFanatic specify `www.youtube.com`
