### ISSUE TITLE
Howto configure keybinding scheme

### ISSUE THREAD

**Issue by nobk** [ueokande/vim-vixen#688]
Can this plugin user define all keybinding to wanted command?

s: up
d: down
space: page dn
shift space: page up
S: prev tab
D: next tab
v: back
V: forward
x: close tab
X: undo close tab
a: click next page link
A:click prev page link
r: refresh
R:force refresh
Alt r: refresh all tabs
t: new tab
and all hints chars can hit by left hand easily 12345qwertasdfgzxcvb

**Comment by AlexeySachkov** [comment]
Hi @nobk,

Of course you can configure vim-vixen keybingins as you want to: open Add-ons manager in the browser (`Ctrl`+`Shift`+`A`), then `Vim-Vixen`, then `Options`

There are two ways to define config: use some GUI form (I've never ever seen it) or use plain JSON (it should be easy to understand/edit).

Default config can always be found in [src/settings/keymaps.ts](https://github.com/ueokande/vim-vixen/blob/7104f122f94e17ece56d2bd832d007c716e5631e/src/settings/keymaps.ts): just in case you broke something or want to use it as reference.

Hintchars can be configured via corresponding property, see [docs](https://ueokande.github.io/vim-vixen/properties.html)
