### ISSUE TITLE
No way to navigate the completion list without poluting the query.

### ISSUE THREAD

**Issue by khalidchawtany** [ueokande/vim-vixen#69]
### I'm opening this issue because:

- [ ] I'll report a bug
- [X] I'll propose a new feature or a bug report idk

### Description
There is no way to navigate the completion suggestions (for :open, :tabopen etc). You can use tab and s-tab however, this changes the query text!

Consider the following scenario:
1. You press `o` and and the `:open` console is shown with a list of suggestions.
2. I type `not` to list all entities that contain `not`
3. I see that the third entity in the list is the one I want and press tab to navigate to it. **BUT this causes the second entry text to become the new query and I loose the third entry I was trying to get to**.

The following patch seems to solve the issue for me. But I am not a react developer and this is just a hack.
[patch.txt](https://github.com/ueokande/vim-vixen/files/1389001/patch.txt)

#### System configuration

- Operating system: Mac OS 10.12.6
- Firefox version: 57.0b8 (64-bit)
- Vim-Vixen version: 0.1

**Comment by ueokande** [comment]
I confirmed to reproduced it by simply pressing Shift + Tab.
