### ISSUE TITLE
Repeating tab removal

### ISSUE THREAD

**Issue by fly1ngDream** [ueokande/vim-vixen#693]
### I'm opening this issue because:

- [X] I'll report a bug
- [ ] I'll propose a new feature

### Failure Information (for bugs)
Repeating tab removal is not working correctly

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open 3 tabs and go to the first one
2. Use `Alt + 3` to jump to the third tab
3. Press `d` (you want to remove the third tab but all 3 tabs are removed and browser is closed)

#### System configuration

- Operating system: 5.4.6-arch1-1
- Firefox version: Mozilla Firefox 72.0b9
- Vim-Vixen version: 0.26

**Comment by ueokande** [comment]
@fly1ngDream 
Thank you for your reporting.  I have been reproduce it.
It will be fixed in next release.

**Comment by fly1ngDream** [comment]
@ueokande OK, thx. Should i close the issue or let it be opened till the next release?

**Comment by ueokande** [comment]
@fly1ngDream Keep it opened until the it is fixed.

**Comment by mwgkgk** [comment]
This applies to any mappings that allow a numerical prefix, e.g. <C-d>, <C-u>, u, resulting in a pretty miserable experience if you're used to navigate tabs via Alt+numbers.

The repeat commands were introduced in #689.

**Comment by ueokande** [comment]
The fixed version is now released!
