### ISSUE TITLE
Can't reopen closed tabs

### ISSUE THREAD

**Issue by Swoogan** [ueokande/vim-vixen#698]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description
Pressing `u` produces "An unexpected error occurred"

#### Steps to Reproduce

1. Close a tab 
2. press `u`
3. Red error bar at bottom of page appears with "An unexpected error occurred"

#### System configuration

- Operating system: Ubuntu 18.04
- Firefox version: 71.0 (64 bit)
- Vim-Vixen version: 0.26

#### Console logs

Any relevant log in developer tools:

**Comment by ueokande** [comment]
I couldn't reproduce it. Are you still experiencing the issue?

**Comment by Swoogan** [comment]
No, it seems to have gone away on its own. Perhaps restarting my browser
fixed it.
