### ISSUE TITLE
Focusing first input on page?

### ISSUE THREAD

**Issue by antgel** [ueokande/vim-vixen#699]
### I'm opening this issue because:

- [ ] I'll report a bug
- [X] I'll propose a new feature

### Description

Thanks for this great add-on, I'm coming from Chromium / vimium... Would it be possible to add similar functionality - by typing `gi`, the first input on the page is focused? Very useful for sites like Google Maps.

**Comment by ueokande** [comment]
Use <kbd>g</kbd><kbd>i</kbd>.  Doesn't it work?

**Comment by antgel** [comment]
Indeed, and I see it's in the docs (not sure if it was when I opened the issue. Thanks!
