### ISSUE TITLE
Reader Mode

### ISSUE THREAD

**Issue by octoninjacat** [ueokande/vim-vixen#70]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description
It would be awesome to have Vim-Vixen work in Reader Mode.

#### System configuration

- Operating system: macOS Sierra 10.12.6
- Firefox version: 56.0 (64-bit)
- Vim-Vixen version: 0.1

**Comment by ueokande** [comment]
It might a limitation of WebExtensions API.

**Comment by ueokande** [comment]
duplicated with #180
