### ISSUE TITLE
[Question] Why Does This Require So Many Permissions? | Privacy Concern

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [ueokande/vim-vixen#706]
I am just wondering, why this requires so many permissions? (History access, etc)
It seems to have a lot of unnecessary permissions.

**Comment by bas080** [comment]
History makes sense actually. Open a new page and you'll see why.

It is opensource so go ahead and see for yourself what these permissions are used for.

Maybe having users define the level of permissions makes sense.

**Comment by ueokande** [comment]
Vim Vixen requires the following permissions:

    history, bookmark ... to open a URL from history, bookmarks
    sessions ... to restore closed tabs.
    tabs ... list, get, and manipulate tabs
    storage ... save settings into local store
    clipboard read ... open a tab from the clipboard
    notification ... notify users the add-on udated
    browser settings ... get user's homepage setting
