### ISSUE TITLE
Loaded settings is invalid: The default settings is used due to the last...

### ISSUE THREAD

**Issue by aleksozolins** [ueokande/vim-vixen#722]
### I'm opening this issue because:
I'm getting an error I don't know how to fix.
- [x ] I'll report a bug
- [ ] I'll propose a new feature

### Description
When I open Firefox I get a lib-notify alert that says "Loaded settings is invalid: The default settings is used due to the last saved settings is invalid. Check your current settings from the add-on preference.

To my knowledge I have not modified any settings from default. I have uninstalled and reinstalled the extension to no avail. Error is happening only on one of my computers. Other computer with same version no problem.

I've also uninstalled and reinstalled Firefox and trashed the preferences.

#### Steps to Reproduce

Just open Firefox.

Please provide detailed steps for reproducing the issue.

#### System configuration
Arch Linux 5.5.5
Firefox 73.0.1
Vim Vixen 0.27

#### Console logs

Any relevant log in developer tools:

**Comment by mschloesser** [comment]
Same issue here.

macOS 10.14.6
Firefox 73.0.1
Vim Vixen 0.27

**Comment by AlexeySachkov** [comment]
I've also faced this issue: for me it seems to be fixed by re-creating a config file: I switched config file from JSON to GUI form and back to get a default config and then applied all my customizations

**Comment by aleksozolins** [comment]
> I've also faced this issue: for me it seems to be fixed by re-creating a config: I switched config file from JSON to GUI form and back to get a default config and then applied all my customizations

I can confirm that this worked for me. Not sure why I didn't try that myself. Thank you!
