### ISSUE TITLE
Shift+K and Shift+J no longer switching tabs

### ISSUE THREAD

**Issue by liamtimms** [ueokande/vim-vixen#723]
### I'm opening this issue because:

- [X] I'll report a bug

### Description

Using Firefox 73.0.1 it appears that the tab switching has stopped working. All other shortcuts seem to work as normally expected. Tab closing, opening and reopening all work, this only seems to affect tab switching. Scrolling with `j` and `k` also continue to work normally. 

### Failure Information (for bugs)

no error output 

#### Steps to Reproduce

1. Use latest vim vixen with firefox 73.0.1
2. attempt to use shift K, J to switch tabs

#### System configuration

- Operating system: Arch Linux x86_64, Kernel 5.5.7-arch1-1
- Firefox version: 73.0.1
- Vim-Vixen version: 0.27

#### Console logs

no console log

**Comment by liamtimms** [comment]
Tried uninstalling and reinstalling vim vixen, had no effect

**Comment by me-benni** [comment]
Had the same issues after using the workaround from #722 
Switching tabs was mapped to `gt` and `gT`.

In your preferences change your entries for switching tabs
```json
"K": {
  "type": "tabs.prev"
},
"J": {
  "type": "tabs.next"
}
```

**Comment by liamtimms** [comment]
@me-benni great thanks, that was the issue.
