### ISSUE TITLE
"/" key bind config missing

### ISSUE THREAD

**Issue by jflorian** [ueokande/vim-vixen#74]
### I'm opening this issue because:

- [X] I'll report a bug
- [ ] I'll propose a new feature

### Description

Looking at the configuration JSON, I do not see where the "/" key is bound to any function.  I don't want to change it, but this seems like an oversight or, at least, incongruous.

#### System configuration

- Operating system: Fedora 26 x86_64
- Firefox version: 57.0b6 (64-bit)
- Vim-Vixen version: 0.1

**Comment by ueokande** [comment]
@jflorian 
Do you mention about "Quick find" by `/` key ?  That is a default feature in Firefox.  But as I disscussed in #76, that may be replaced Vim Vixen's feature.

**Comment by jflorian** [comment]
@ueokande Huh!  I never would've guessed Firefox itself was handling the `/` key.  Then again, it's not like I've ever used Firefox "as shipped".  How could I know such things?  :-)

I was about to suggest maybe putting a comment in the default JSON config to remind those like me about this particular case, but then remembered that JSON doesn't do comments.  Probably best just to make it a native Vim Vixen feature as you suggest -- that'd solve it for good.

**Comment by ueokande** [comment]
The default key bindings in Firefox are presented in the following:
https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly
Vim Vixen bindings must work just for keys contained in JSON.

**Comment by ueokande** [comment]
close this issue because duplicated in #1
