### ISSUE TITLE
Allow disabling ctrl + f

### ISSUE THREAD

**Issue by heatherbooker** [ueokande/vim-vixen#747]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description
I know `ctrl` + `f` is overwritten and we are supposed to use `/` for search (related: #88). However, old habits die hard, and sometimes I press ctrl + f by accident, then start typing, and all other commands follow my keystrokes and I end up closing tabs, deleting emails, and generally wreaking havoc.

Can there be a way to disable the ctrl + f keybinding that vim vixen implements?

Thanks!

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. press ctrl + f out of habit
2. start typing a random word without waiting
3. everything is bad! :(

#### System configuration

- Operating system: Fedora
- Firefox version: 75.0
- Vim-Vixen version: 0.27

#### Console logs

Any relevant log in developer tools:

**Comment by AtomToast** [comment]
You should be able to just disable this in the preferences.  

Got to `about:addons` and select Vim-Vixen. Then go over to the preferences tab and remove the corresponding line containing <C-F> or just replace it with something else

**Comment by heatherbooker** [comment]
I couldn't find any line with ctrl-f; is every single binding supposed to exist in that preferences section?

**Comment by AtomToast** [comment]
Okay, I didn't check when sending that message but apparently github did not render the keyboard shortcut rendering. What I meant to say was:

... Then go over to the preferences tab and remove the corresponding line containing `<C-F>` or just replace it with something else  

`<C-F>` is just a different notation form than ctrl+f

**Comment by heatherbooker** [comment]
Wow, awesome. I assumed the `F` actually mean capital F, I guess I should have tried it. Thank you!!
