### ISSUE TITLE
follow links does not work with filesystem links

### ISSUE THREAD

**Issue by Jorgeromeu** [ueokande/vim-vixen#759]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description
The follow links feature does not work with local filesystem links. When it is attempted the following is retunred:

![image](https://user-images.githubusercontent.com/40536127/81858103-7e362500-9563-11ea-9413-4c80abb8a606.png)

### Failure Information (for bugs)
n/a

#### Steps to Reproduce
Simply create a local site with a hyperlink and run it in firefox with the extension enabled. Attempt to follow the link. As a minimum example, a directory with the files 

```
demo
├── index.html
└── other.html
```
```html
<!-- index.html -->

<!DOCTYPE html>

<html>
  <body>
    <a href="other.html">link<a>
  </body>
</html>
```
`other.html` can be anything. Attempt to follow the link with `fa`

#### System configuration

- Operating system: linux, ubuntu 18.04
- Firefox version: 76.0.1
- Vim-Vixen version:0.29

#### Console logs
n/a

**Comment by fosskers** [comment]
Note that this also occurs when you try to open a `file://` link that's in your bookmarks. It attempts to visit `www.file.com///....`

**Comment by ueokande** [comment]
It is an API limitation to prevent security issues. See #264
