### ISSUE TITLE
"n" and "N" do not search for next match

### ISSUE THREAD

**Issue by jflorian** [ueokande/vim-vixen#76]
### I'm opening this issue because:

- [X] I'll report a bug
- [ ] I'll propose a new feature

### Description

I have come to rely heavily on pressing "n" for the next forward-search match and "N" for the next backwards-search match, but Vim-Vixen does not seem to yet support that.  Perhaps the default JSON config is just missing a few critical lines.  If so, I don't know what they should look like.

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

#### System configuration

- Operating system: Fedora 26 x86_64
- Firefox version: 57.0b6 (64-bit)
- Vim-Vixen version: 0.1

#### Console logs

Any relevant log in developer tools:

**Comment by ueokande** [comment]
@jflorian Thank you for the proposal.  The implementation is not so easy, because there is no way to access search on the page by WebExtensions API.  In Vimium, that seems searching on the page is implemented by itself.
Of course I also want to search by `n`/`N`, so that may be supported in the future 😃

**Comment by jflorian** [comment]
@ueokande Thanks for the explanation.  I hadn't guessed this would be a limitation of the API, but my awareness of the limitations is only from that of add-ons user since I've never even looked at the sources for one of these.

**Comment by kashperanto** [comment]
@ueokande I was also about to say this was a bug/missing feature until I saw that / is Firefox's native quickfind key.  It is unfortunate that search is not a part of the API (seems like an oversight to me).  Perhaps you could add a section to the main README to inform people about '/', and tell them that 'ctrl-g' is the equivalent of 'n'.  You will certainly save others from searching for the search feature (hah) in the config files or code (I was almost certain that you had a binding until I discovered the quickfind feature was natively mapped to '/' and was still there when I disabled this plugin).

Thank you for making this plugin.  You don't realize how reliant you become on the vim bindings until you can't have them.

**Comment by ueokande** [comment]
I had not expected that feature is not so generally known. I'd like to describe it in README.

**Comment by ueokande** [comment]
close this issue because it will support in #1
