### ISSUE TITLE
Scrolling up does not work when displaying the lowest part (bottom) of a page

### ISSUE THREAD

**Issue by gobenji** [ueokande/vim-vixen#825]
### I'm opening this issue because:

- [ x ] I'll report a bug

### Description
Scrolling up using vim-vixen does not work when displaying the lowest part (bottom) of a page. That is, it seems like the scrollbar gets stuck at the bottom. It is possible to use "normal" means of scrolling up (ex. mouse wheel) and that gets vim-vixen unstuck until going to the bottom of the page again.

#### Steps to Reproduce

1. Open a website that is longer than one screen (ex: https://www.bunniestudios.com/);
2. Scroll to the bottom of the page (using 'j', or 'shift+g' or mouse wheel, or scrollbar, ...);
3. Try to scroll up using 'k' or 'ctrl-u' or 'ctrl-b' -> it does not work, nothing moves
4. Try to scroll up using 'up arrow' or 'page up' or mouse wheel, or scrollbar, ... -> it works
After the view has been moved up a little bit from the bottom, it is possible to use 'k' and others to scroll up and down again. But if moving all the way to the bottom of the page, it gets stuck again.

#### System configuration

- Operating system: Debian Unstable using the openbox window manager
- Firefox version: 80.0
- Vim-Vixen version: 0.30

Note that I tried this in a new firefox profile where I only installed vim-vixen and reproduced the issue.

#### Console logs

Any relevant log in developer tools: None (no new messages at all at that time)

**Comment by LeonT-A** [comment]
I've also been having this issue, not on every page, but frequently.

By default, Shift + Space goes up a page, so when I have this issue I try to remember to use that since it's easily accessible. Most of the times though I'll forget and reach for my mouse.

**Comment by femnad** [comment]
From bisecting #755 seems to be the trigger for this behavior, however, I haven't found a way to address this issue without reintroducing #267.

**Comment by sierratango88** [comment]
Same issue here.

Some web pages that I've seen this bug include:

1. https://en.wikipedia.org/wiki/Main_Page
2. https://music.youtube.com
3. https://github.com/enkore/j4-dmenu-desktop

**Comment by phi-gamma** [comment]
Fwiw this I also observe this with horizontal movement at the bottom right corner of say a zoomed
image file. Bottom left corner is fine, you can move right using ``l``. The bottom right corner locks up
and you can’t move left by pressing ``h``.

**Comment by apiraino** [comment]
> From bisecting #755 seems to be the trigger for this behavior, however, I haven't found a way to address this issue without reintroducing #267.

cc: @MatiasStorm - perhaps can shed insights on this regression?

**Comment by MatiasStorm** [comment]
Thank you @apiraino for bringing this to my attention.
I have found  the cause of the bug and are currently working on a solution.

**Comment by ueokande** [comment]
resolved  #900
