### ISSUE TITLE
Run plugin at page opened

### ISSUE THREAD

**Issue by ueokande** [ueokande/vim-vixen#83]
### I'm opening this issue because:

- [ ] I'll report a bug
- [X] I'll propose a new feature

### Description
Current plugin runs after a page get to be idle.  We have to wait to complete loading the page. `run_at` property in manifest.json allows to set timing for running content scripts.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open heavy page, loading not still completed
2. Press `j`
3. Scroll down

#### System configuration

- Operating system: Linux
- Firefox version: v57 developer edition
- Vim-Vixen version: 0.2

#### Console logs

Any relevant log in developer tools:

**Comment by anonymouzz** [comment]
Also this happens when open page and try to switch to other tab.

**Comment by ueokande** [comment]
`run_at` is set `""document_idle"` in default;  the document and all its resources have finished loading.
https://developer.mozilla.org/ja/Add-ons/WebExtensions/manifest.json/content_scripts#run_at
