### ISSUE TITLE
Domain/Page exclusion/disable

### ISSUE THREAD

**Issue by Bankq** [ueokande/vim-vixen#87]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description
It'd be nice if I can configure vim-vixen to not be triggered on certain domains (e.g gmail with its own keybinding).

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

#### System configuration

- Operating system:
- Firefox version:
- Vim-Vixen version:

#### Console logs

Any relevant log in developer tools:

**Comment by ueokande** [comment]
duplicated in #11

**Comment by ueokande** [comment]
duplicated in #11

**Comment by Bankq** [comment]
@ueokande thanks, will track #11 instead.
