### ISSUE TITLE
'f' key conflicts with 'cmd + f' search function

### ISSUE THREAD

**Issue by caesarjuly** [ueokande/vim-vixen#88]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description
I find that 'cmd +f' doesn't work on my mac book. When I press these two keys, the 'f' key works instead. This is really annoying.

#### System configuration
- Operating system:
macOS Sierra 10.12.6
- Firefox version:
firefox version 57.0b10
- Vim-Vixen version:
0.2
#### Console logs

Any relevant log in developer tools:

**Comment by linnik** [comment]
I can't find mention of this in documentation, but maybe you should use `/` keybinding for search?

**Comment by ueokande** [comment]
`/` is a Firefox's bindings.
https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_search

**Comment by caesarjuly** [comment]
@linnik @ueokande Thank u guys. After a few months without vim, I almost forget to use`/`. I works well.

**Comment by pengux** [comment]
How do you go to the next occurrence with Quick Find? Pressing Cmd+G doesn't work

**Comment by linnik** [comment]
@pengux cmd+G works for me. [docs](https://support.mozilla.org/en-US/kb/search-contents-current-page-text-or-links)

**Comment by jubalh** [comment]
According to Firefox info I run vim vixen 0.7, but `/` in combination with `n` for the next result still don't work for me.

**Comment by pengux** [comment]
@jubalh Try cmd + G

**Comment by jubalh** [comment]
right, so `n` will not be implemented I guess?
