### ISSUE TITLE
[Feature Request] Completion to search the bookmarks URL instead of the name

### ISSUE THREAD

**Issue by lucasmsoares96** [ueokande/vim-vixen#898]
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description

Add a configuration option for "completion" to search the bookmarks URL instead of the name. Since some favorites are not saved with a name.

![image](https://user-images.githubusercontent.com/60808407/99028614-f4393a00-254e-11eb-9600-e934ec25d33c.png)

**Comment by snprajwal** [comment]
The completion matches both the URL and the name, depending on what you search. If the name is not there, it will default to searching the URL.
