### ISSUE TITLE
Cannot search on page

### ISSUE THREAD

**Issue by pengux** [ueokande/vim-vixen#91]
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description
Pressing Cmd+f activates the "follow.start" operation instead of the search on page feature in Firefox

**Comment by idhindsight** [comment]
You should be using / to search, not ctrl-f.

**Comment by ueokande** [comment]
duplicated in #88

**Comment by tiagolr** [comment]
muhhuhhaha
