### ISSUE TITLE
Does not work in local web pages

### ISSUE THREAD

**Issue by ogkloo** [ueokande/vim-vixen#92]
- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description
vim-vixen does not work on local web pages. I don't know if this is expected behavior- vimium works on them, so I assume not.

#### Steps to Reproduce
Go to a website starting with `file://...` and attempt to use vim-vixen.

#### System configuration
- Operating system: Ubuntu 16.04
- Firefox version: 58.0a1 (Nightly)

**Comment by ueokande** [comment]
It might a limitation of WebExtensions API.

**Comment by wasamasa** [comment]
Same thing seems to be the case for the "New Tab" page.

**Comment by ainola** [comment]
@ueokande is correct in that this is a webextention limitation. Vimium works around this issue slightly by making the new tab page some placeholder blank page so that it can still work. It is far from ideal but it is something.

**Comment by ueokande** [comment]
This is issue is cloed in 1a873ce9c3245ad0d397cbf85035889ceb442290 and already fixed at version 0.4.
