### ISSUE TITLE
[Feature Request] vim-vixen for Firefox ReaderView 

### ISSUE THREAD

**Issue by mohamadali-halwani** [ueokande/vim-vixen#927]
### I'm opening this issue because:

- [ ] I'll report a bug
- [*] I'll propose a new feature

### Description

Greetings Development team,
First, I'd like to thank you for this great tool. It genuinely helps!!!
I happen to use the readerview in firefox while reading, and it occurred to me that vim-vixen's keybindings do not work there. It would be convenient to use vim-vixen in readerview.
I hope you can consider it.
Kind Regards.
Mohamadali

**Comment by apiraino** [comment]
Not 100% sure but I'm afraid this cannot be done. Firefox in ReaderMode takes full control and disables all extensions.

There are some situations in which the web extensions API are disabled, I believe this is one of them

**Comment by mohamadali-halwani** [comment]
> There are some situations in which the web extensions API are disabled, I believe this is one of them

Thank you for your reply.
Isn't there a way to bypass that? And if not, can't we propose such a feature to Firefox?

**Comment by apiraino** [comment]
I wish this was possible :-) I think one of the main complains of the new web extensions API introduced in firefox 57 was that they crippled features used by extensions to highly customize the browser. I think [Vimperator](http://vimperator.org/) was one of these casualties.

To my knowledge there's no going back, Mozilla is not going to expose any new API for that level of customization

**Comment by mohamadali-halwani** [comment]
Oh this is sad to hear.
Thanks again, I'll close this issue
