### ISSUE TITLE
Implement "Focus Form Input"

### ISSUE THREAD

**Issue by ainola** [ueokande/vim-vixen#98]
### I'm opening this issue because:

- [ ] I'll report a bug
- [X] I'll propose a new feature

### Description
Other vim-like addons map `gi` to focus input to a form. I'm particularly fond of vimium's implementation in which the first field will be selected but tab will cycle through the other input fields with a nice little graphic to show where you are.

Also, in my personal opinion, I do not enjoy the implementations where the contents of the field are selected when using `gi` (as VimFX implemented) as the need for all of the contents to be selected are much rarer than just needing to append to existing text.

Also also, I'm fond of the option to block websites from stealing input focus on load.

Thanks for your great work, @ueokande. I didn't expect such a bombshell extension to drop like this!

**Comment by rexkerr** [comment]
It would be nice if this also worked with a count, like 2gi to go to the second input field on the page.

**Comment by helpermn** [comment]
Please implement this as it is very useful feature that was available in vimfx.

**Comment by alanlxl** [comment]
Agree! `gi` is pretty useful, without it I must type `f` and the hint to do this...
